### ISSUE TITLE
Newtonsoft.Json.dll release incompatible versions with same strong name

### ISSUE THREAD

**Issue by spahnj** [JamesNK/Newtonsoft.Json#1001]
Please review [issue #615](https://github.com/JamesNK/Newtonsoft.Json/issues/615) and also see [this topic.](http://stackoverflow.com/questions/31608983/newtonsoft-json-net-version-incompatibility-dll-hell)

Our application uses a local reference to Newtsonsoft.Json.dll version 8.02.
Another application (from a different company) installed Newtsonsoft.Json.dll version 8.03 into the GAC.

It totally broke our application.  Json.Net has worked flawlessly for us otherwise and has been able to handle everything we've thrown at it.
This is the only issue we've ever really had with Json.Net.  The issue has occurred a bunch of times over that past few years and I finally figured out what was going on.  

I thought it was something I was doing wrong.
Hopefully you're in a better mood this year...

Cheers!

**Comment by JamesNK** [comment]
Every approach to strong naming has issues. This is the issue of the approach I've chosen.

**Comment by bondarchook** [comment]
This is known issue 
http://stackoverflow.com/questions/31608983/newtonsoft-json-net-version-incompatibility-dll-hell

**Comment by bondarchook** [comment]
@JamesNK 
If it is not hard, can you please explain why did you chose this approach for versioning?

Because from user point of view it looks absolutely insane. Different companies can brake each other software without even knowing about that. And end-user can not resolve this conflicts at all.   

Thank you.

**Comment by kendallb** [comment]
James, can you comment on your approach and why you feel it is the right solution for json.net? I personally have not run into this issue because we only ever bin deploy code to our web servers and do not use json.net for any desktop apps that might have this issue.

From what I can work out you feel having a single strong version that remains x.0.0.0 (like the current 9.0.0.0 I am using) is good and you just change the file version. But if there are incompatible changes, won't that mean stuff breaks as mentioned above if somehow the DLL is shared in the GAC? While I do agree putting stuff in the GAC is a really bad idea, it's what we have and a lot of stuff gets deployed in the GAC at install time whether we like it or not.

I believe what is being requested is that for every new build the file version increases, which is what I see for all the other projects we use via NuGet. Can you explain why you feel that is a bad idea?

**Comment by markusschaber** [comment]
We  had similar problems with other assemblies, or solution was to build  ourself, using our own snk file, so we get our own "strong name". That  way, we can make sure we have unique version numbers, and the framework  cannot load wront assemblies because it prefers GAC to local  installation directory. It's a shame that applications cannot suppres loading from GAC (or at  least repriorize GAC to be searched after local directories...)
