### ISSUE TITLE
StringEnumConveter with CamelCaseText not camel casing enum values

### ISSUE THREAD

**Issue by bleggett** [JamesNK/Newtonsoft.Json#1028]
This is with Newtonsoft.Json v 9.0.1. 

I've got an object with a property on it that looks like this:

```
[JsonProperty(PropertyName = "dataType")]
[JsonConverter(typeof(StringEnumConverter))]
public DataType ColumnDataType { get; internal set; } = DataType.Text;
```

The DataType enum looks like this:
```
namespace MetaDataCreator.Lists
{
    //Consider splitting this out and sharing these types with form fields.
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataType
    {
        LocalShortDate,
        LocalVerboseDateTime,
        Numeric,
        Currency,
        Decimal,
        Boolean,
        Text
    }
}
```
And I'm serializing the object like this:
```
var result = JsonConvert.SerializeObject(value, Formatting.Indented, new StringEnumConverter { CamelCaseText = true});
```
I would expect this code, based on the attributes I applied, to turn 
```
ColumnDataType = DataType.LocalShortDate
```
into
```
"dataType": "localShortDate"
```
But it does not, the enum string is serialized to "LocalShortDate".

I have also tried putting built-in .Net serialization attribs on the enum values, and that also did not work.

```
namespace MetaDataCreator.Lists
{
    //Consider splitting this out and sharing these types with form fields.
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DataType
    {
        [EnumMember(Value = "localShortDate")]
        LocalShortDate,
        [EnumMember(Value = "localVerboseDateTime")]
        LocalVerboseDateTime,
        [EnumMember(Value = "numeric")]
        Numeric,
        [EnumMember(Value = "currency")]
        Currency,
        [EnumMember(Value = "decimal")]
        Decimal,
        [EnumMember(Value = "boolean")]
        Boolean,
        [EnumMember(Value = "text")]
        Text
    }
}
```
Am I doing something wrong here, or is this a bug? I feel like this should work.

**Comment by TylerBrinkley** [comment]
There's a precedence for `JsonConverter`'s that you need to understand. Below is the precedence order.

1. `Property` (`JsonConverterAttribute` on `ColumnDataType`)
2. `Type` (`JsonConverterAttribute` on `DataType`)
3. `JsonSerializerSettings` (`JsonConverter` in `Converters`)

Since you have specified converters on all three, the `JsonConverterAttribute` on the property `ColumnDataType` takes precedence and since `CamelCaseText` is not specified then you don't get camel-casing. I'd suggest you remove the `JsonConverterAttribute` on the property `ColumnDataType` and the enum `DataType`, then your `JsonSerializerSettings`' `Converters` will take precedence.

Perhaps this needs to be added to the documentation on the `Converters` section of the `Serialization Settings` guide.

**Comment by bleggett** [comment]
Ah, missed that. Thanks!
