### ISSUE TITLE
Int parsing not working properly 

### ISSUE THREAD

**Issue by ajaychoudhary01** [JamesNK/Newtonsoft.Json#1057]
We are passing 0000011 or 011 or 0011 etc in integer type parameter (C#). It is getting de-serialized to 9. 
If we are passing 000012 or 012 or 0012 etc it is getting de-serialized to 10.

Please check this issue.

**Comment by ajaychoudhary01** [comment]
Version 6.0,3, using with Web API 2.2

**Comment by JamesNK** [comment]
They're octal.

**Comment by richarddbarnett** [comment]
This seems to violate the JSON spec: http://json.org/.
See also http://stackoverflow.com/questions/29048110/override-json-deserializing-a-number-with-a-leading-zero-as-a-decimal-and-not-an

**Comment by JamesNK** [comment]
Yes it does, but Json.NET allows some non-JSON spec things when reading JSON.

When writing JSON it conforms to the spec.

**Comment by crawley** [comment]
You shouldn't have done that (see my answer to the StackOverflow question).  However, since you did that you should at least document the non-standard extensions that you have made to the JSON spec.  I can't find any mention of the word "octal" when I search the Json.NET(using the search box here: http://www.newtonsoft.com/json/help/html/Introduction.htm)  So I presume that it is not documented.

I would also suggest that you implement a "strict" option to turn off your non-standard extensions.  In this case, it should treat leading zeros as an error, since that is what the JSON spec says.

**Comment by IonutStef** [comment]
Hello! 

I just encountered this "problem". 
Was there added something to make it work?

Thank you!
Stefan

**Comment by ajaychoudhary01** [comment]
@lonutstef, we changed type to string and converted to int in API code.

**Comment by IonutStef** [comment]
@ajaychoudhary01 Thank you for response! 
So the problem shouldn't be encountered anymore, or it was decided to remain like this?
