### ISSUE TITLE
Skip serialization of empty collections

### ISSUE THREAD

**Issue by matkoch** [JamesNK/Newtonsoft.Json#1118]
I'm using a custom `ContractResolver` in oder to skip empty collections during object graph serialization. My naive assumption was to use `ShouldSerialize`, but it turns out, that there is no clear relation between the `JsonProperty` and the object being passed to the delegate. What I was expecting to write was something like:

    protected override JsonProperty CreateProperty ([NotNull] MemberInfo member, MemberSerialization memberSerialization)
    {
      var property = base.CreateProperty(member, memberSerialization);
      if (typeof(ICollection).IsAssignableFrom(property.PropertyType)
          && property.PropertyType != typeof(string))
        property.ShouldSerialize = x => ((ICollection) x).Count > 0;

      return property;
    }

But it is obviously the parent object. If I want to stay type-independent, I need to use the `MemberInfo` instance inside that action; therefore creating a closure and using reflection to retrieve the value. Is there any better way to achieve that?

Secondly, I can see that the code is mostly duplicated for `ShouldSerialize` and `GetIsSpecified`. Any reason for that?

**Comment by dbc2** [comment]
_Is there any better way to achieve that?_

You could use `property.ValueProvider.GetValue(x)` to get the value from within the `ShouldSerialize` delegate.  See for example the `CreateProperty()` method in [this answer](http://stackoverflow.com/a/38043874/3744182).

*Secondly, I can see that the code is mostly duplicated for `ShouldSerialize` and `GetIsSpecified`. Any reason for that?*  Probably because `XmlSerializer` supports both:

 - `XmlSerializer` documentation for the `ShouldSerialize` pattern is [here](https://msdn.microsoft.com/en-us/library/53b8022e.aspx).  Json.NET added support in [version 3.5.7](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/3.5.7). 

- `XmlSerializer` documentation for the `Specified` pattern is [here](https://msdn.microsoft.com/en-us/library/zds0b35c.aspx).  Json.NET added support for the pattern in [4.0.1](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/4.0.1).

**Comment by JamesNK** [comment]
Well answered
