### ISSUE TITLE
Json Schema Specification (Version 4) support

### ISSUE THREAD

**Issue by gsferreira** [JamesNK/Newtonsoft.Json#115]
Hi,

When do you expect to support the Json Schema Specification (Version 4)?

**Comment by br15** [comment]
Hi,

I've downloaded the code and built solution just fine.  However I need to integrate your code with a .Net 4.0 solution which I can't (for political reasons) upgrade to .Net 4.5 which is the version you've used with your solution.

Any chance you could create a .Net 4.0 version with an associated NuGet  package for Newtonsoft.Json 7.0.1-beta1.

Cheers

**Comment by JamesNK** [comment]
I'll look at adding .NET 4. Probably shouldn't be an issue.

FYI there is a limit on the number of schema validations per hour without a license. I should have a website ready for buying a license in a couple of weeks but I wouldn't recommend using it in a live environment until then.

**Comment by br15** [comment]
Hi James,

Thanks for the quick response.  I'll definitely be buying a license.
What's the current limit set to for validation per hour?
Could you please notify me as soon as the .Net 4.0 support is available.

Cheers
Keith.

Great work by the way.

**Comment by JamesNK** [comment]
1000 an hour, resetting each time you run an application or rebuild a website. Lots for development purposes.

I've added .NET 4.0 support and uploaded a beta release to myget here: https://www.myget.org/F/json-net/api/v2

It uses a new feature I've added to json.net that hasn't been released yet so that will be updated to a beta version as well.

**Comment by br15** [comment]
That was quick. Marvellous!

 

Cheers 

Keith

**Comment by br15** [comment]
Hi James,

The link to the .Net 4 code doesn't seem to work. I just get this in the browser:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom" xml:base="https://www.myget.org/F/json-net/api/v2/">
<workspace>
<atom:title>Default</atom:title>
<collection href="Packages">
<atom:title>Packages</atom:title>
</collection>
<collection href="Screenshots">
<atom:title>Screenshots</atom:title>
</collection>
</workspace>
</service>

**Comment by JamesNK** [comment]
It's a NuGet feed URL. You don't download from it using a browser, you need to add it as a package source to the NuGet Package Manager in Visual Studio.

http://docs.nuget.org/docs/start-here/managing-nuget-packages-using-the-dialog#Package_Sources

Name is up to you, source is https://www.myget.org/F/json-net/api/v2

**Comment by br15** [comment]
Hi James,

When I try to install the package I get an error:

Install failed. Rolling back...
Failed to initialize the PowerShell host. If your PowerShell execution
policy setting is set to AllSigned, open the Package Manager Console to
initialize the host first.


I found a couple of articles on stackoverflow that suggested setting an
execution policy to RemoteSigned or Unrestricted . When I go to the NuGet
Console (Tools | NuGet Package Manager | Package Manager Console) to try to
change the execution policy to unrestricted I get:

PM> Set-ExecutionPolicy Unrestricted
Execution Policy Change
The execution policy helps protect you from scripts that you do not trust.
Changing the execution policy might expose you to the security risks
described in the about_Execution_Policies help topic. Do you want to change
the execution policy?
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):Y
Set-ExecutionPolicy : Windows PowerShell updated your execution policy
successfully, but the setting is overridden by a policy defined at a
 more specific scope.  Due to the override, your shell will retain its
current effective execution policy of "RemoteSigned". Type "Get-Exec
utionPolicy -List" to view your execution policy settings. For more
information, please see "Get-Help Set-ExecutionPolicy."
At line:1 char:20
+ Set-ExecutionPolicy <<<<  Unrestricted
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy],
SecurityException
    + FullyQualifiedErrorId :
ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
PM>

Any suggestions?

Cheers
Keith

**Comment by JamesNK** [comment]
I found this: http://stackoverflow.com/questions/23353951/cant-install-nuget-package-because-of-failed-to-initialize-the-powershell-host

**Comment by JamesNK** [comment]
If you are still having problems with NuGet then the dlls can now be downloaded in a zip file as well: https://github.com/JamesNK/Newtonsoft.Json.Schema/releases

**Comment by br15** [comment]
Thanks

**Comment by digitalgym** [comment]
I am also in urgent need of 0.4 schema support, does the 1.0.1-beta3 release contain support for this?

**Comment by JamesNK** [comment]
Yes

**Comment by digitalgym** [comment]
Ok thanks, I have the .dll referenced how do I get JsonSchemaGenerator to output the v4 schema?

**Comment by JamesNK** [comment]
JSchemaGenerator

Pretty much the API is exactly the same as v3, except JsonSchema has been replaced with JSchema.

**Comment by fractos** [comment]
Awesome. Just in time for me needing it :)

**Comment by JamesNK** [comment]
Json.NET Schema is now on nuget.org

https://www.nuget.org/packages/Newtonsoft.Json.Schema

**Comment by br15** [comment]
Hi James,

I've been doing some tests on the new v4 schema validation support and I come across an issue.  I'm sending JSON request to a well known web portal.  As part of their client validation process they provide a set of v4 schemas for the various request types they support and an valid example of each of the JSON requests so that users of their API can perform some sanity checks.
When I run their test requests through my code using Json.NET some of the requests fail validation.

The  portal says they have run the sample through http://json-schema-validator.herokuapp.com and 
and https://github.com/Julian/jsonschema . Both report no errors.  I've included below both the v4 schema and the test JSON request. This is the smallest request and schema that failed.  Json.Net reported the validation error in the errorList as:
"JSON is valid against more than oneschema from 'oneOf'. Valid schema indexes: 0, 1. Line 1, position 1.

JSON Request:

{
   "branch_reference" : "zpg_test_1",
   "branch_name" : "XXX Test Branch",
   "location" : {
      "property_number_or_name" : "65",
      "street_name" : "Some Street",
      "town_or_city" : "London",
      "postal_code" : "SEX 0HR",
      "country_code" : "GB"
   },
   "email": "members@xxx.co.uk",
   "website" : "http://www.xxx.co.uk/"
}

V4 Schema:

{
   "$schema" : "http://json-schema.org/draft-04/schema#",
   "title" : "branch/update",
   "type" : "object",
   "additionalProperties" : false,
   "id" : "http://realtime-listings.webservices.xxx.co.uk/docs/v0.1/schemas/branch/update.json",
   "definitions" : {
      "coordinates" : {
         "type" : "object",
         "additionalProperties" : false,
         "properties" : {
            "latitude" : {
               "type" : "number",
               "minimum" : -90,
               "maximum" : 90
            },
            "longitude" : {
               "type" : "number",
               "minimum" : -180,
               "maximum" : 180
            }
         },
         "required" : [
            "latitude",
            "longitude"
         ]
      }
   },
   "properties" : {
      "branch_name" : {
         "type" : "string",
         "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
      },
      "branch_reference" : {
         "type" : "string",
         "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
      },
      "email" : {
         "type" : "string",
         "pattern" : "@"
      },
      "location" : {
         "type" : "object",
         "additionalProperties" : false,
         "properties" : {
            "property_number_or_name" : {
               "type" : [
                  "integer",
                  "string"
               ],
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "street_name" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "locality" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "town_or_city" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "county" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "postal_code" : {
               "type" : "string",
               "pattern" : "^\\S(|(.|\\n)*\\S)\\Z"
            },
            "country_code" : {
               "type" : "string",
               "pattern" : "^[A-Z]{2}(-[A-Z0-9]{1,3})?$"
            },
            "coordinates" : {
               "$ref" : "#/definitions/coordinates"
            },
            "paf_address" : {
               "type" : "object",
               "additionalProperties" : false,
               "properties" : {
                  "address_key" : {
                     "type" : "string",
                     "pattern" : "^[0-9]{8}$"
                  },
                  "organisation_key" : {
                     "type" : "string",
                     "pattern" : "^[0-9]{8}$"
                  },
                  "postcode_type" : {
                     "enum" : [
                        "L",
                        "S"
                     ]
                  }
               },
               "required" : [
                  "address_key",
                  "organisation_key",
                  "postcode_type"
               ]
            },
            "paf_udprn" : {
               "type" : "string",
               "pattern" : "^[0-9]{8}$"
            }
         },
         "required" : [
            "street_name",
            "town_or_city",
            "country_code"
         ]
      },
      "telephone": {
         "type" : "string",
         "pattern" : "[0-9]+"
      },
      "website" : {
         "type" : "string",
         "pattern" : "^[Hh][Tt][Tt][Pp][Ss]?://\\S+$"
      }
   },
   "required" : [
      "branch_reference",
      "branch_name",
      "location"
   ],
   "oneOf" : [
      { "$ref" : "#/constraints/gb" },
      { "$ref" : "#/constraints/overseas" }
   ],
   "constraints" : {
      "gb" : {
         "properties" : {
            "location" : {
               "properties" : {
                  "country_code" : {
                     "pattern" : "^GB"
                  },
                  "postal_code" : {
                     "pattern" : "^[A-PR-UWYZ][A-HJ-Y]?[0-9][0-9A-HJKMNPR-Y]? [0-9][ABD-HJLNP-UW-Z]{2}$"
                  }
               },
               "required" : [
                  "postal_code"
               ]
            }
         }
      },
      "overseas" : {
         "properties" : {
            "location" : {
               "properties" : {
                  "country_code" : {
                     "not" : {
                        "pattern" : "^GB"
                     }
                  }
               }
            }
         }
      }
   }
}

**Comment by JamesNK** [comment]
I've created an issue in the schema project: https://github.com/JamesNK/Newtonsoft.Json.Schema/issues/3

**Comment by JamesNK** [comment]
Website is up: http://www.newtonsoft.com/jsonschema
Documentation: http://www.newtonsoft.com/jsonschema/help

**Comment by pcibraro** [comment]
I've read about the FOSS exception for your new project jsonschema, but I have a concern. If I include a reference to jsonschema in my open source project. Based on your understanding, is the AGPL license transitive to any commercial software written by my open source project as well ?. It would be great if you can clarify that for me, as I'm looking for a way to support json schema in one of the open source projects where I am currently working on.

Thanks

**Comment by vojtechvit** [comment]
I am a bit sad that I can't use JSON schema validation draft v4 within Json.NET because the pricing of the Json.NET Schema is way too high to justify the expense to our management since it's a single-purpose library and just a nice-to-have in most scenarios. Please consider some licensing or pricing changes..

**Comment by rsuter** [comment]
Maybe you are interested in this alternative project: https://github.com/NJsonSchema/NJsonSchema
