### ISSUE TITLE
Question - How to report error in customized JsonConverter's ReadJson

### ISSUE THREAD

**Issue by wjzhou** [JamesNK/Newtonsoft.Json#1196]
In my code, I want to have a customize converter that can read Vector2 from json array. For example, 
``` json
{ "a": [1.0,0.0] }
```
``` csharp
class T {
  Vector2 A {get;set;}
}
```

How do I report the lineNumber and LinePosition when the input is invalid? 
JsonSerializationException.Create or JsonReaderException.Create are internal methods.

For now, I use the following code. But I hope there are better and cleaner standard way. 
``` csharp
private void ThrowError(JsonReader reader, string message)
{
    IJsonLineInfo lineInfo = reader as IJsonLineInfo;
    if (lineInfo!=null && lineInfo.HasLineInfo())
    {
        message = $"{message}. Path '{reader.Path}', line {lineInfo.LineNumber}, position {lineInfo.LinePosition}.";
    }
    throw new JsonSerializationException(message);
}
```

**Comment by JamesNK** [comment]
Looks fine to me.

**Comment by kevinoid** [comment]
I realize this issue is long-closed, but I wanted to second @wjzhou's (implied) request for a way to instantiate `JsonSerializationException` with `IJsonLineInfo`.  It seems like a common need and reimplementing or copying `JsonSerializationException.Create` and `JsonPosition.FormatMessage` is not ideal.  For example, the proposed code above doesn't actually set `Path`, `LineNumber`, or `LinePosition` on the created exception.

Any chance you might consider making `JsonSerializationException.Create` public?

**Comment by lostincomputer** [comment]
I agree that there should be a public way to instantiate a  `JsonSerializationException` with `IJsonLineInfo`. It's strange that built-in `JsonConverter`s such as `StringEnumConverter` can call `JsonSerializationException.Create` but custom `JsonConverter`s can't.

**Comment by AntonC9018** [comment]
This should be reopened IMO

**Comment by rjgotten** [comment]
Running into this myself as well right now.
So help me; I'm considering just breaking encapsulation and using reflection to tap into the internals.

**Comment by danielschilling-ml** [comment]
There now appears to be a `public JsonSerializationException(string message, string path, int lineNumber, int linePosition, Exception? innerException)` constructor. I'm not sure what version introduced it.
