### ISSUE TITLE
Add support for Xamarin.Mac

### ISSUE THREAD

**Issue by mattrichnz** [JamesNK/Newtonsoft.Json#1335]
Unfortunately JSON.Net does not yet target Xamarin.Mac to add support for macOS.

See known issues.
https://blog.xamarin.com/preview-bringing-macos-to-xamarin-forms/

> Not All NuGets are Ready for macOS
> In order to work in a macOS project, packages must target xamarinmac20. You may find that some of your beloved libraries do not yet support macOS. What can you do? Kindly send a request to the project’s maintainer to add it. Until they have support, you may need to look for alternatives.

**Comment by TylerBrinkley** [comment]
.NET Standard, which Json.NET targets, was created in order to prevent requiring library authors from having to update their libraries to target new platforms. Other Xamarin platforms implement .NET Standard, surely this one does too right? If not, you should contact the Xamarin guys to try to get them to implement .NET Standard for Xamarin.Mac?

**Comment by JamesNK** [comment]
Does macOS not support netstardard?

My POV is if you want Newtonsoft.Json support on a new platform then that platform should support netstandard. That's what it is for.

**Comment by mattrichnz** [comment]
Thanks @JamesNK 
Xamarin have advised that Xamarin.Mac will support .NET Standard when it hits v2.0.
https://forums.xamarin.com/discussion/comment/282041#Comment_282041
