### ISSUE TITLE
Cannot read/write optional enum with custom converter

### ISSUE THREAD

**Issue by schani** [JamesNK/Newtonsoft.Json#1490]
### Source/destination types

```csharp
    public partial class TopLevel
    {
        public FooBar FooBar { get; set; }
        public FooBar? MaybeFooBar { get; set; }
    }

    public enum FooBar { Foo, Bar };
```

I'm using a converter to read and write the `FooBar` enum values as strings `"foo"` and `"bar"`.

### Source/destination JSON

    { "FooBar": "foo", "MaybeFooBar": "foo" }

### Expected behavior

    {"FooBar":"foo","MaybeFooBar":"foo"}

### Actual behavior

    {"FooBar":"foo","MaybeFooBar":0}

### Steps to reproduce

Download the project [optional-bug.zip](https://github.com/JamesNK/Newtonsoft.Json/files/1450490/optional-bug.zip), unzip and do

    dot net run test.json

**Comment by JamesNK** [comment]
The second property is `FooBar?` but your converter will only return with `FooBar`

    public override bool CanConvert(Type t) => t == typeof(FooBar);

**Comment by schani** [comment]
Other `Nullable` types are converted by default without issue.  Why is this different with an enum?  Do I have to write converters for every type that contains custom enums, like `List<FooBar>`?

**Comment by TylerBrinkley** [comment]
`List` is a reference type and is always nullable but enums are value types hence the need to check for `FooBar?` You can see [here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/DateTimeConverterBase.cs#L44) the built-in `DateTime` converters must check for their nullable versions explicitly because `DateTime` is also a value type.
