### ISSUE TITLE
pairs/ValueTuples don't preserve names when serializing

### ISSUE THREAD

**Issue by wizofaus** [JamesNK/Newtonsoft.Json#1505]
It's reasonable to expect

JsonConvert.SerializeObject( (Name: "MyPair", Value: 123) ) 

to produce 
{ "Name":"MyPair", "Value":123 }

but currently it outputs { "Item1":"MyPair", "Item2":123 }

Unfortunately from what I can read currently there's nothing that can actually be done about this as the field names are erased at runtime.  But if this is incorrect or is remedied in a future version of C#, I'd say it's a worthwhile enhancement.

**Comment by WildCard65** [comment]
#1230

**Comment by JonHanna** [comment]
I don't agree that is reasonable to expect. The code in your example is compiled to the same thing as
```C#
JsonConvert.SerializeObject(new ValueTuple<string, int>("MyPair", 123));
```
So it isn't reasonable to expect `SerializeObject` to do anything else.

Following property metadata could perhaps be done, and would also solve a problem this doesn't, since you could just have used an anonymous object here anyway, but that isn't the case when properties or fields return tuples.

**Comment by wizofaus** [comment]
Duplicate.

**Comment by mcintyre321** [comment]
Dupe of https://github.com/JamesNK/Newtonsoft.Json/issues/1230
