### ISSUE TITLE
Newtonsoft.Json.JsonConvert.SerializeObjectInternal does not dispose StringWriter

### ISSUE THREAD

**Issue by HubertoKusters** [JamesNK/Newtonsoft.Json#1564]
Hi,

This is actually a question. Shouldn't the private Newtonsoft.Json.JsonConvert.SerializeObjectInternal method dispose the instance of StringWriter to prevent memory-leaks? 

Like so:

```
private static string SerializeObjectInternal(object value, Type type, JsonSerializer jsonSerializer)
{
    StringBuilder sb = new StringBuilder(256);
    using (StringWriter sw = new StringWriter(sb, CultureInfo.InvariantCulture))
    using (JsonTextWriter jsonWriter = new JsonTextWriter(sw))
    {
        jsonWriter.Formatting = jsonSerializer.Formatting;
        jsonSerializer.Serialize(jsonWriter, value, type);
        return sw.ToString();
    }
}
```

**Comment by JonHanna** [comment]
No need. `StringWriter` inherits `Dispose()` from `TextWriter`, which it has because it's common for `TextWriter` implementation to have some sort of unmanaged resource either directly or (more often) indirectly via an object like a `Stream`, and it's useful to be able to access the necessary clean-up through a `TextWriter` reference. But since `StringWriter` just appends to a `StringBuilder` there's no unmanaged resource and the implementation either (depending on version) does nothing or just sets a boolean field, so if you know the `TextWriter` is in fact a `StringWriter` you can safely leave out the `Dispose()` as a very minor optimisation.

**Comment by JamesNK** [comment]
If it was a `StreamWriter`, or an unknown implementation of `TextWriter` then dispose would need to be called, but it isn't needed with `StringWriter`.
