### ISSUE TITLE
ImmutableStack should roundtip

### ISSUE THREAD

**Issue by JohanLarsson** [JamesNK/Newtonsoft.Json#1596]
The following test fails:

```cs
[Test]
public void RoundtripStack()
{
    var stack = ImmutableStack.CreateRange(new[] {1, 2, 3});
    var roundtripped = JsonConvert.DeserializeObject<ImmutableStack<int>>(JsonConvert.SerializeObject(stack));
    CollectionAssert.AreEqual(stack, roundtripped);
}
```

I can PR a fix for it but correcting it is a breaking change.

**Comment by JamesNK** [comment]
I'm pretty sure this has come up before. The problem is the results when enumerating over ImmutableStack is the reverse of how items need to be ordered when pass to the method that creates an ImmutableStack. Regular `Stack<T>` does the same thing.

If you want to work around this I think you either use a type other than Stack, or you write a JsonConverter the reverses results.

**Comment by khionu** [comment]
Shouldn't it be the responsibility of the lib to be able to handle CoreFx collections properly?

**Comment by forki** [comment]
@jamesnk why did you close it? Shouldn't we aim for json serializer to do correct round tripping?
