### ISSUE TITLE
Bug deserialization of object returns null

### ISSUE THREAD

**Issue by ByK95** [JamesNK/Newtonsoft.Json#1650]
### Source/destination types

```csharp
    public class DivideToSomeNum : ViewValueInterface
    {
        public int division { get; set; }
        string ViewValueInterface.PrettifyView(int? rawValue)
        {
            if(rawValue == null)
            {
                return "No Connection";
            }
            else if (division != 0)
            {
                return (rawValue / division).ToString();
            }
            return rawValue.ToString();
        }
    }
"instance of DivideToSomeNum class stored as "object" type in another class"
    public class Sample
    {
        public object itemV2 { get; set; }
        public string getText()
        {
            return JsonConvert.SerializeObject(itemV2);
        }
        public static Sample GetSample(string jsonText)
        {
            return JsonConvert.DeserializeObject<Sample>(jsonText);
        }
    }

```

### Source/destination JSON

```javascript
{"division":100}
```

### Expected behavior

Instance of a class casted into object 

### Actual behavior

No cast at all,deserialized object is null

### Steps to reproduce

```csharp
Sample test = new Sample {itemV2 = new DivideToSomeNum { division = 100 } };
string Text= test.getText();
Sample sample = Sample.GetSample(Text);
```

**Comment by qpooqp** [comment]
Hello.
_Before my actuall comment i want to clarify that i'm not affiliated with Newtonsoft.Json. I'm just random guy from internet trying to help._

First something which is not clear to me. Why do you have **itemV2** as object (data type).
```csharp
public object itemV2 { get; set; }
```
I think it is not good practice to store objects in object data type (boxing, unboxing) unless there is some really strong reason to do so. I think much better would be to use interface/base class/generics but i don't know what is your code used for so if you **know** that you need boxing then ignore this comment.
One more problem to this is that Newtonsoft.Json can't tell how to deserialize the value to original object, because it can't know which object it was.
Because of that it will make it as JObject. (you can see it in file Newtonsoft.Json.Serialization.JsonSerializerInternalReader on line 457)
```csharp
if (HasNoDefinedType(contract))
{
    return CreateJObject(reader);
}
```


### Now to your problem. 
In your class sample you are first serializing property **itemV2** which is of type `DivideToSomeNum` (boxed to `object`).
```csharp
public object itemV2 { get; set; }
public string getText()
{
    return JsonConvert.SerializeObject(itemV2);
}
```
But then you are deserializing it to type `Sample`.
```csharp
return JsonConvert.DeserializeObject<Sample>(jsonText);
```
This is the reason that the property **itemV2** is null. 
So this is just bug in your code. 

I hope that this answer helps you or anyone whou would read this.
