### ISSUE TITLE
IsoDateTimeConverter - always append Z or explicit timezone, to avoid browser incompatibilities

### ISSUE THREAD

**Issue by sinelaw** [JamesNK/Newtonsoft.Json#172]
Due to [an issue in ES5.1](https://bugs.ecmascript.org/show_bug.cgi?id=112), browsers have [different interpretations of ISO-8601 dates](http://stackoverflow.com/questions/15109894/new-date-works-differently-in-chrome-and-firefox/15110385#comment30743117_15110385) that are missing a trailing timezone (neither 'Z' nor explicit timezone value).

Currently, IsoDateTimeConverter does not set 'Z' when serializing a DateTime object that was created without a DateTimeKind.UTC parameter:

```
var date = new DateTime(2009, 2, 15, 0, 0, 0, DateTimeKind.Local);
var settings = new JsonSerializerSettings();
settings.Converters.Add(new IsoDateTimeConverter());

// Succeeds
Assert.IsTrue(JsonConvert.SerializeObject(date.ToUniversalTime(), settings).EndsWith("Z\""));

// Fails
Assert.IsTrue(JsonConvert.SerializeObject(date, settings).EndsWith("Z\""));
```

To make it easier to work with output from Json.NET, it should always append the 'Z' (or set an explicit timezone) when converting dates to strings in IsoDateTimeConverter.

The easiest fix is to use the result of `.ToUniversalTime()` on each date object when serializing it (as shown above).

**Comment by grennis** [comment]
I was thrown off by this because the documentation page shows it does append a trailing Z:

http://www.newtonsoft.com/json/help/html/DatesInJSON.htm

Shows: "Details":"Application started.","LogDate":"2009-02-15T00:00:00Z" ... But the actual output is not that - It does not have a trailing Z. I was able to get the Z without calling ToUniversalTime by settings this option in the serializer settings:

    _jsonSettings.DateTimeZoneHandling = DateTimeZoneHandling.Utc;

Probably just a documentation issue.

**Comment by bjorn-ali-goransson** [comment]
@grennis , the docs are maybe unclear but not incorrect. It doesn't say that it always appends a Z, it says it uses the ISO format. That is, Z for UTC dates, but not all dates are UTC.

It later states:

> set DateTimeZoneHandling to Utc to serialize all DateTimes as UTC dates

Which implies that non-UTC dates will not be serialized as UTC dates. :)

**Comment by divmgl** [comment]
So does JSON.net append a Z or not? I'm doing some tests and it looks like it isn't appending a Z.

**Comment by AntiTenzor** [comment]
I could not believe the issue is **almost 8 years(!)** and the library does not provide strict specialized **UtcDateTimeConverter** to manage DateTime conversions in a convenient "no-doubt" style!

Could you please help me to implement **UtcDateTimeConverter** ?
a) Every incoming DateTime must be serialized to full format with UTC time-zone.
**always UTC with clear indication of this**.
    I.e.   "2021-11-17**T**04:38:47.1168339**Z**"
    
b) Deserialization must return DateTime **always in UTC**.
