### ISSUE TITLE
JsonExtensionData does not support IReadOnlyDictionary<T>

### ISSUE THREAD

**Issue by shravan2x** [JamesNK/Newtonsoft.Json#1742]
Using code like the following currently results in an exception:

```c#
 [JsonExtensionData]
public IReadOnlyDictionary<string, JToken> Extra { get; private set; }
```

```
Unhandled Exception: Newtonsoft.Json.JsonException: Invalid extension data attribute on 'App.Core+DataModel'. Member 'Extra' type must implement IDictionary<string, JToken>.
```

Could support be added for `IReadOnlyDictionary`?

**Comment by JamesNK** [comment]
No. Extension data is designed to add the data to a dictionary. If there is no way to add data then it cannot work.

**Comment by shravan2x** [comment]
@JamesNK But isn't this basically the same as an `ImmutableDictionary<T, V>` which does work?

**Comment by JamesNK** [comment]
An immutable dictionary works as extension data?

**Comment by shravan2x** [comment]
I was confused, immutable dictionary does not seem to work as extension data.

But I'm curious, why did you decide to disallow `ReadOnlyDictionary` and `ImmutableDictionary` as extension data, but allow them for regular properties? Couldn't they just be handled the same way?

**Comment by kmcclellan** [comment]
I think the issue here is that collection properties should generally either be readonly (no setter) OR modifiable, not both (c.f. [`CA2227`](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227)). Because [JSON extension data requires a setter](https://github.com/dotnet/runtime/issues/32197), I would expect to be able to use a non-modifiable (i.e. "readonly") collection type.

Note, I say "non-modifiable" to avoid confusion with `ImmutableDictionary<TKey, TValue>` (mentioned above), which implements `ICollection<>` and is therefore modifiable in the sense I mean here. Using `ImmutableDictionary<TKey, TValue>` as JSON extension data will make it past the type check on deserialization, but throws `NotSupportedException` when `Add(...)` is invoked.
