### ISSUE TITLE
UnixDateTimeConverter serialization bug

### ISSUE THREAD

**Issue by marioleed** [JamesNK/Newtonsoft.Json#1744]
It seems like the UnixDateTimeConverter offsets the time with one hour on serialization. Tested on two different computers. I switched from `Microsoft.Azure.Documents.UnixDateTimeConverter` which does this correctly.

### Source/destination types

```csharp
public class MyClass
{
    [JsonConverter(typeof(UnixDateTimeConverter))]
    public DateTime Start { get; set; }
}
```

### Expected behavior

`JsonConvert.SerializeObject(input)` should return `{"Start":662688000}`.

### Actual behavior

`JsonConvert.SerializeObject(input)` returns `{"Start":662684400}`

### Steps to reproduce

```csharp
var input = new MyClass 
{ 
    Start = DateTime.Parse("1991-01-01 00:00:00", CultureInfo.InvariantCulture) 
};

var jsonOutput = JsonConvert.SerializeObject(input);
var result = JsonConvert.DeserializeObject<MyClass>(jsonOutput);

Assert.AreEqual(input.Start, result.Start);
```

**Comment by marioleed** [comment]
It seems to boil down to `DateTimeKind.Utc`. If it's anything other than Utc it will fail.

**Comment by tuscen** [comment]
I think it actually works correctly. You're trying to convert datetime with `DateTimeKind.Unspecified` to a unix timestamp (which is in UTC+0 by definition). To do that the converter first translates the date to a UTC+0 and `ToUniversalTime` treat `Unspecified` dates as local dates. As a result anything other than `DateTimeKind.Utc` after subsequent deserialization won't be equal to the original datetime in .NET because that's how `DateTime` in .NET is designed.

If your example works with `Microsoft.Azure.Documents.UnixDateTimeConverter` I'd say that it doesn't work correctly with anything other than `DateTimeKind.Utc` and results with incorrect unix timestamps.

**Comment by marioleed** [comment]
Yep, you're right. Thanks.
