### ISSUE TITLE
Application freeze/deadlock when attempting JsonConvert.DeserializeObject<Task<Foo>>

### ISSUE THREAD

**Issue by TilkID** [JamesNK/Newtonsoft.Json#1886]
### Source/destination types

```csharp
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace TestNewtonSoft
{
    class Program
    {
        public class Foo { }

        static void Main(string[] args)
        {
            // As Task<T> is not serializable but wait for it
            var serialization = JsonConvert.SerializeObject(Task.FromResult(new Foo()));
            // serialization = "{"Result":{},"Id":1,"Exception":null,"Status":5,"IsCanceled":false,"IsCompleted":true,"CreationOptions":0,"AsyncState":null,"IsFaulted":false}"

            /* Newtonsoft.Json Version >= 4.5.1 => This line is stalling application
               Newtonsoft.Json Version < 4.5.1  => Newtonsoft.Json.JsonSerializationException: 'Unable to find a constructor to use for type System.Threading.Tasks.Task`1[TestNewtonSoft.Program+Foo]. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Line 1, position 10.' */
            var deserialization = JsonConvert.DeserializeObject<Task<Foo>>(serialization);
        }
    }
}
```

### Expected behavior

Throw an exception like versions < 4.5.1. Anything else than a freeze/deadlock of the application

### Actual behavior

SerializeObject succeeds in converting to JSON even if Task<T> is not ISerializable: That could be useful.
While calling JsonConvert.DeserializeObject => Application freeze, like it would with a deadlock: CPU 0% / RAM is stable.

### Steps to reproduce

Create a simple project in VS and use above code

**Comment by oddbear** [comment]
It doesn't make much sense to serialize and deserialize a Task. If this gets implemented, then the serialization should be async, to not block.

I would have expected an exceptions in this particular case.

But this might be related to https://github.com/JamesNK/Newtonsoft.Json/issues/1798

**Comment by JamesNK** [comment]
Don't serialize/deserialize a task.

**Comment by im-scared** [comment]
hello. i ran into this today and it was super frustrating. it would have been nice to get an exception indicating that you can't deserialize a task, rather than the application freezing :T

i wouldn't normally deserialize a task, but didn't know any de/serialization was happening until i debugged, because it was happening in a library i was using. would have been a lot easier to debug if i got an exception like "attempting to deserialize a Task, which is not deserializable".

is it possible to protect against this within `JsonConvert` and throw an exception?
