### ISSUE TITLE
CamelCasePropertyNamesContractResolver does not work with JToken

### ISSUE THREAD

**Issue by Kunze** [JamesNK/Newtonsoft.Json#1908]
### Source/destination types

```csharp
public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddJsonOptions(options =>
            {
                options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseMvc();
        }
    }

    public class ValuesController : Controller
    {
        [HttpGet("")]
        public IActionResult Get()
        {
            var jToken = JToken.FromObject(new
            {
                Name = "name"
            });

            return Ok(jToken);
        }
    }
```

### Expected behavior
The serialized object should be:
`{
     "name": "name"
}`

### Actual behavior
The serialized object has a capital letter:
`{
     "Name": "name"
}`

**Comment by JamesNK** [comment]
That's expected behavior. JToken is already JSON. Contract resolver is for converting .NET types to JSON, and camel casing is for changing the .NET property names to JSON property names.

You need to convert JToken's yourself prior to serializing, or write a JsonConverter for them.

**Comment by danielbarla** [comment]
(I'm not sure if this is the most appropriate place to post this, but this ticket came up pretty high on a search for this exact problem / use case, so I thought others might find it useful.)

A valid use case is to convert unknown, pascal cased JSON to (still unknown) camel cased JSON. The above explanation about JObject and its expected behaviour makes sense, although it can be somewhat surprising, especially when the explicit `JsonConvert.SerializeObject(unknownJObject, ... CamelCasePropertyNamesContractResolver...)` form is used.  In this case, it may seem impossible to solve the stated problem with JsonConvert without writing more code.

Luckily, at least one trivial solution exists, by switching out JObject for ExpandoObject (e.g. `JsonConvert.DeserializeObject<ExpandoObject>(unknownJson)`.
