### ISSUE TITLE
Serialized class to JArray

### ISSUE THREAD

**Issue by TheConsciousness** [JamesNK/Newtonsoft.Json#1937]
Hello! Great work on the library! I am having a simple issue that you could probably answer in your sleep.

Serializing an object works really really well, but I would like to add each of my serialized strings to a JArray so that I can form myself a valid JSON array. However upon doing so, I am getting a double-serialized output.
`[
  "{\"Lot\":\"SA12345678\",\"Inspector\":\"Inspector\",\"RPN\":\"Something\",\"Date\":\"11/16/18\",\"Time\":\"7:00 a.m.\",\"Sample\":\"1\",\"Displacement\":\"0.12\",\"Force\":\"1.14\"}"]`

I populate my object with values, then I serialize the object to get the Lot, RPN, etc, valid JSON string. Upon getting that I use **jArray.Add(JsonConvert.SerializeObject(newRow));**, which generates that double-quoted string above.

The only way I can resolve this issue is to use **jArray.Add(JsonConvert.DeserializeObject(JsonConvert.SerializeObject(newRow)));**, which seems redundant. Would you know of a method that works better than serializing and serializing? Thank you.

**Comment by dbc2** [comment]
In order to add a non-primitive POCO to a `JArray`, you need to explicitly serialize it to a `JToken`.  Your deserialize/serialize combination accomplishes this, but a better solution is to use [`JTokenFromObject(newRow)`](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_FromObject.htm):

    jArray.Add(`JTokenFromObject(newRow));

See: [Could not determine JSON object type for type “Class”](https://stackoverflow.com/a/40728452/3744182) and [With NewtonSoft, how to create an array of strings with JArray](https://stackoverflow.com/a/35465349/3744182).
