### ISSUE TITLE
Problem with deserialization when constructor has default argument

### ISSUE THREAD

**Issue by slava-osipov-qs** [JamesNK/Newtonsoft.Json#2070]
I have a base abstract class for futher derived classes that need to be serialized/deserialized
All derived classes has their own properties to serialize/deserialize, but the problem is not in the derived classes

```csharp
public abstract class LogEntry
{
        // preferred constructor declaration... see below
        protected LogEntry(DateTime? timeStamp = null)
        {
            TimeStamp = timeStamp??DateTime.Now;
        }
        
         // must not be changed in any way except deserialization or constructor
        public DateTime TimeStamp { get; }

        public string Serialize()
        {
            return JsonConvert.SerializeObject(this, 
                new JsonSerializerSettings(){TypeNameHandling = TypeNameHandling.All});
        }
        public static LogEntry Deserialize(string json)
        {
            return JsonConvert.DeserializeObject(json, new JsonSerializerSettings()
            {
                TypeNameHandling = TypeNameHandling.All
            }) as LogEntry;
        }
        public abstract void SomeFunc(); // to be impelemneted in derived class
}
```

LogEntry object must be immutable once it is created, so I can't allow TimeStamp public setter.
The actual problem - I do not see a way to force calling of constructor with argument during deserialization. 
Probably here is another way to solve the problem of deserialization of immutable objects.

P.S. Actually I've found a work around with current implementation:
declare TimeStamp as 
```csharp
public DateTime TimeStamp { get; private set; } // add explicitly private setter to declaration
```
But it is very non obvious and implementation dependent.

Is there any way to have a predictable way to ensure that privately defined data can be deserialized... preferably by constructor only?

**Comment by dbc2** [comment]
Can't reproduce, see https://dotnetfiddle.net/4PizI8.

Can you share a full [Minimal, Complete, and Verifiable example](https://github.com/JamesNK/Newtonsoft.Json/issues/2070)? 

Note that https://dotnetfiddle.net/ only supports c# 4.0 so I had to make `TimeStamp` an explicit property:

		readonly DateTime m_timeStamp;
		public DateTime TimeStamp { get { return m_timeStamp; } }

I also had to set `TypeNameAssemblyFormatHandling` to `TypeNameAssemblyFormatHandling.Full` because https://dotnetfiddle.net/ executes user code in partial trust which restricts loading of types by name to fully qualified assembly names.

However, neither of these changes should affect your issue.

Incidentally, you have a security flaw in `Deserialize()`: you should deserialize to the base type `LogEntry` rather than to something untyped.  Your current code allows an attacker to trick your code into instantiating an *attack gadget*.  For why, see 

 - [TypeNameHandling caution in Newtonsoft Json](https://stackoverflow.com/q/39565954/3744182).
 -  https://www.blackhat.com/docs/us-17/thursday/us-17-Munoz-Friday-The-13th-JSON-Attacks-wp.pdf
 - [External json vulnerable because of Json.Net TypeNameHandling auto?](https://stackoverflow.com/q/39565954/3744182).

The security risk can be ameliorated by using typed deserialization:

		public static LogEntry Deserialize(string json)
		{
			return JsonConvert.DeserializeObject<LogEntry>(
				json, new JsonSerializerSettings()
				{
					TypeNameHandling = TypeNameHandling.All
				});
		}

**Comment by slava-osipov-qs** [comment]
Thanks for your quick responce. 
Please find the project for issue reproducing on [JSONTest](https://github.com/slava-osipov-qs/JSONTest)
Security problem is not an issue in my project, thanks for warning.

**Comment by dbc2** [comment]
I was able to reproduce your problem in a fiddle [here](https://dotnetfiddle.net/hnZCsU).

Your problem is that your derived class `LE2` does not contain a parameterized constructor that allows `TimeStamp` to be set, e.g. as shown below:

    public class LE2 : LogEntry2
    {
        public LE2(DateTime? timeStamp = null) : base(timeStamp) { }

        public override void SomeFunc() {}
    }

In c#, base class parameterized constructors are [not automatically inherited by derived classes](https://stackoverflow.com/q/2095749/344280), so you need to add the constructor explicitly.   Having done so, Newtonsoft will call the parameterized constructor, matching JSON property names to argument names as explained [here](https://stackoverflow.com/q/23017716) and [here](https://www.newtonsoft.com/json/help/html/JsonConstructorAttribute.htm).  But with neither a parameterized constructor nor a setter for `TimeStamp`, there's no possible way for Json.NET to set a value for it.

Demo fixed fiddle [here](https://dotnetfiddle.net/0J1GLV).

I'd recommend closing this.

**Comment by slava-osipov-qs** [comment]
Ok, thanks for detailed explanation. I guess we should close this issue.
