### ISSUE TITLE
Not selecting token based upon complex Json Path having && operator

### ISSUE THREAD

**Issue by jbhano** [JamesNK/Newtonsoft.Json#2074]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```

### Source/destination JSON
{
    "store": {
        "book": [
            {
                "category": "reference",
                "author": "Nigel Rees",
                "title": "Sayings of the Century",
                "price": 8.95
            },
            {
                "category": "fiction",
                "author": "Evelyn Waugh",
                "title": "Sword of Honour",
                "price": 12.99
            },
            {
                "category": "fiction",
                "author": "Herman Melville",
                "title": "Moby Dick",
                "isbn": "0-553-21311-3",
                "price": 8.99
            },
            {
                "category": "fiction",
                "author": "J. R. R. Tolkien",
                "title": "The Lord of the Rings",
                "isbn": "0-395-19395-8",
                "price": 22.99
            }
        ],
        "bicycle": {
            "color": "red",
            "price": 19.95
        }
    },
    "expensive": 10
}
```javascript


JArray o = JArray.Parse(@content) // where content contains above JSON
JToken token = o.SelectToken("$..book[?(@.price==8.99 && @.category=='fiction')]")



```

### Expected behavior

It should return token having
[
   {
      "category" : "fiction",
      "author" : "Herman Melville",
      "title" : "Moby Dick",
      "isbn" : "0-553-21311-3",
      "price" : 8.99
   }
]

### Actual behavior

It's not returning anything in token i.e. token is null. I have checked in other manual parsers, I get expected JSON with this JSONPath

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by dbc2** [comment]
The code in your question throws an exception because the root object in your JSON is not an array, it's an object, and thus `JArray.Parse()` fails.  See https://dotnetfiddle.net/aAIV3J.

If I change that line to `JToken.Parse()` I can't reproduce the problem, see https://dotnetfiddle.net/ic1iBy.  

What version of Json.NET are you using? The above fiddles use 12.0, and in [9.0.1](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/9.0.1) there was an item

<blockquote>
 - Fix - Fixed various bugs in JSONPath equals and not equals comparisions
</blockquote>

which might be related.

**Comment by jbhano** [comment]
I understand the issue here.

Thanks!
