### ISSUE TITLE
Double object curly braces possibly in debugger output

### ISSUE THREAD

**Issue by mwpowellhtx** [JamesNK/Newtonsoft.Json#2154]
Perhaps my eyes are deceiving me, in the latest `Newtonsoft.Json` package, I've got the following `JsonConverter` serialization code:

```C#
var @object = new JObject(
    new JProperty(nameof(value.OutputDirectory), value.OutputDirectory)
    , new JProperty(nameof(value.Items), new JArray(SerializeDescriptors(value).ToArray<object>()))
);
@object.WriteTo(writer);
```

Which debugger *stringification* yields this:

```
{{
  "OutputDirectory": "91e8ed9d-2c0b-4f77-a855-78d328853192\\obj",
  "Items": [
    {
      "AssemblyPath": "..."
    }
  ]
}}
```

Are the double curly braces a feature and/or bug in the debugger *stringification*, or are there really double curly braces going on? Strictly speaking, we've got the one `JObject` going on, so I would be surprised if there was a [*JSON*](http://json.org/) object within an object in the end product.

Curiously enough, `@object.ToString()` does not show the same, consistently, nor does, `$"{@object.ToString()}"`.

```
"{\r\n  \"OutputDirectory\": \"91e8ed9d-2c0b-4f77-a855-78d328853192\\\\obj\",\r\n  \"Items\": [\r\n    {\r\n      \"AssemblyPath\": \"...\"\r\n    }\r\n  ]\r\n}"
```

And, respectively:

```
"{\r\n  \"OutputDirectory\": \"91e8ed9d-2c0b-4f77-a855-78d328853192\\\\obj\",\r\n  \"Items\": [\r\n    {\r\n      \"AssemblyPath\": \"...\"\r\n    }\r\n  ]\r\n}"
```

Given the above verification, I am inclined to think the former, and that `Newtonsoft.Json` is most likely doing the right thing.

Debugging in *VS2017*.

Cheers, and thank you!

**Comment by dovisutu** [comment]
I don't know well about the *stringification* in VS2017, but it shall be a format *feature* of it.
The *stringification* of an object is `{...}`, with the main content in it. For example, tbe stringification of a `JsonReader` pointing at `// comment` in a `JToken` is `{ comment}`. Since the main content of JObject is the JSON string, it shows double curly braces, one for the stringification format, one for the actual JSON string.
And the stringification of a string.is `"..."`, with the real content inside (as if you write a string in the code). Since both `@object.ToString()` and `$"{@object.ToString()}"` are strings, they only show 1 curly brace.

**Comment by mwpowellhtx** [comment]
This was pretty much my conclusion as well. Sorry for the confusion.
