### ISSUE TITLE
StringEnumConverter not working with .net core 3.0

### ISSUE THREAD

**Issue by basslagter** [JamesNK/Newtonsoft.Json#2171]
Just upgraded to .net core 3.0 and it looks like my enum props are no longer converted to string:

```
public class User
{
        public string Id { get; set; }

        public string Name { get; set; }

        [JsonConverter(typeof(StringEnumConverter))]
        public Language Language { get; set; }
}

 public enum Language
 {
        None,
        NL,
        EN,
        DE,
    }
```

Expect to return "NL", "EN", etc. but got 1, 2, etc.
Was working before on core 2.2

**Comment by bartelink** [comment]
Chances are this is because you're using the System.Text.Json serializer now; while it has a large feature overlap, it definitely won't honor `Newtonsoft.Json.JsonConverterAttribute` tags (I believe there is a system.text.json equivalent). One way of maintaining backcompat in the short term is to tell aspnet.core to use the json.net serializer as it previously did (lots of apps will do this for a long time - it's not like it's outlawed or is going to stop working)

**Comment by basslagter** [comment]
That could be the case indeed. I added 'AddNewtonsoftJson()' in the ConfigureServices method after AddControllers (even tried AddMvc) but no luck. Do I have to do something else?
