### ISSUE TITLE
Deserialization problem any help ?

### ISSUE THREAD

**Issue by melakhvision** [JamesNK/Newtonsoft.Json#2426]
My Root class is 
    public class Root
    {
        [JsonProperty("code")]
        public int Code { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

The Data Class is 
    public class Data
    {
        [JsonProperty("timings")]
        public Timings Timings { get; set; }

        [JsonProperty("date")]
        public Date Date { get; set; }

        [JsonProperty("meta")]
        public Meta Meta { get; set; }
    }

I properly deserialize my root object like : 

salatjson = e.Result;

Root model =JsonConvert.DeserializeObject<Root>(salatjson);

I just want to create a List<Timings> from model ?

Please help me ?  

There are thousands of Json.NET questions on Stack Overflow with the json.net tag.

GitHub issues are only for reporting bugs, not questions or help.

-->

### Source/API 
http://api.aladhan.com/v1/timings/:date_or_timestamp?latitude=51.508515&longitude=-0.1254872

```csharp
// Put the types you are serializing or deserializing here

Deserialize Root class
salatjson = e.Result;

Root model =JsonConvert.DeserializeObject<Root>(salatjson);

I get the data nice .
I want to create List<Timings> from model.


#### It's not nan issue I need help but don't know where to post it

I need help please? How can I get it

**Comment by mudassir014** [comment]
@melakhvision 
you get a single object of Timings from the api call, so it would deserialize into a single object too naturally. I don't know what are you trying to achieve here. If you could explain a little more what you need maybe I will be able to help you.

Also, I would suggest you should close this issue because this isn't one in the first place. And a good place to ask such a question could be stackoverflow.
