### ISSUE TITLE
ALEPH-2018004 - DOS vulnerability

### ISSUE THREAD

**Issue by thomasvdb** [JamesNK/Newtonsoft.Json#2457]
We're using [BlackDuck](https://www.blackducksoftware.com) to scan our projects and recently Newtonsoft.Json was flagged as a medium security risk (BDSA-2018-5195) because of the following issue:

> Newtonsoft.Json is vulnerable to denial-of-service (DoS) due to a stack overflow that can occur whenever nested objects are being processed. A remote attacker could cause a vulnerable application to crash by causing it to process a maliciously crafted JSON object.

The BDSA record points to this article which was created around 2018: https://alephsecurity.com/vulns/aleph-2018004
I've been searching for more information about this issue but can't find anything useful.

Do you have any more information about this?
The article states that the issue has been communicated. Has this been fixed or what's your opinion about this?

**Comment by Silurus** [comment]
@thomasvdb I was fighting with the same problem and probably found a way how to mitigate it by setting the **MaxDepth** serializer setting to 64 (or any other value you expect for your nesting object level)
https://www.newtonsoft.com/json/help/html/MaxDepth.htm

Instead of a stack overflow, you will get a JsonReaderException thrown by the Newtonsoft library.

![DoS solution](https://user-images.githubusercontent.com/19695435/105361655-f84a9d80-5c0a-11eb-99a7-535006fb8faf.PNG)

**Comment by JamesNK** [comment]
Yes, MaxDepth setting is designed for this situation.

**Comment by Silurus** [comment]
@JamesNK maybe it is worth to set the default MaxDepth value for the json library? Do you have such plans?
I'm just worrying about other people who don't know about this vulnerability and they still might use the library to deserialize some generalized types like "object"

**Comment by igoravila-net** [comment]
The latest Microsoft.Azure.CognitiveServices.Vision.ComputerVision version is 7.0.1 which has a Newtonsoft.Json dependency that uses v10.0.3 which is vulnerable
I'm running a SAST scan that recommends to update Newtonsoft.Json to v13.0.1 but the dev team can't make this update
How can I mitigate this vulnerability?
https://nvd.nist.gov/vuln/detail/CVE-2024-21907
![Image](https://github.com/user-attachments/assets/9254b846-e892-43cd-9086-4a9b4a0410a9)
