### ISSUE TITLE
long JToken numbers are trimmed

### ISSUE THREAD

**Issue by LukAss741** [JamesNK/Newtonsoft.Json#2508]
this code:

```
Console.WriteLine(JToken.Parse("[1234567890123456789]")[0].Value<decimal>());
Console.WriteLine(JToken.Parse("[0.123456789012345678901234567890]")[0].Value<decimal>());
Console.WriteLine(JToken.Parse("[1234567890.12345678901234567890]")[0].Value<decimal>());
Console.WriteLine(JToken.Parse("[12345678901234567890.1234567890]")[0].Value<decimal>());
Console.WriteLine(JToken.Parse("[1234567890123456789]")[0].Value<double>());
Console.WriteLine(JToken.Parse("[0.123456789012345678901234567890]")[0].Value<double>());
Console.WriteLine(JToken.Parse("[1234567890.12345678901234567890]")[0].Value<double>());
Console.WriteLine(JToken.Parse("[12345678901234567890.1234567890]")[0].Value<double>());
Console.WriteLine(JObject.Parse("{\"a\":1234567890.12345678901234567890}")["a"].Value<decimal>());
```

returns this

```
1234567890123456789
0,123456789012346
1234567890,12346
12345678901234600000
1,23456789012346E+18
0,123456789012346
1234567890,12346
1,23456789012346E+19
1234567890,12346
```

why are the values trimmed?

**Comment by elgonzo** [comment]
> why are the values trimmed?

Because `JToken.Parse` / `JObject.Parse` uses an internal `JsonTextReader` for parsing the json text which operates in `FloatParseHandling.Double` mode by default. And you are not able to change the mode of this internal JsonTextReader from the "outside", unfortunately. :-(

However, there are alternatively ways to read Newtonsoft.Json.Linq jtoken types with `Decimal` for floating point numbers, until this limitation is (hopefully) being eliminated.

One such way is leveraging the `JToken.Load` method, which accepts a `JsonReader`. Thus, FloatParseHandling mode of this JsonReader can be set to Decimal accordingly like:
```
string jsonText = ...
using var jsonRdr = new JsonTextReader(newStringReader(jsonText)) { FloatParseHandling = FloatParseHandling.Decimal };
var jtoken = JToken.Load(jsonRdr);
```

Another way would be using `JsonConvert.Serialize` instead of `JToken.Parse`, with the FloatParseHandling mode of the default serialization settings set to Decimal:

```
JsonConvert.DefaultSettings =
    ( ) => new JsonSerializerSettings
    {
        FloatParseHandling = FloatParseHandling.Decimal
    };

string jsonText = ....
var jtoken = JsonConvert.DeserializeObject<JToken>(jsonText);
```
Note that it in this particular case it is sufficient to specifiy `JToken` as the deseralization target type. The correct matching concrete Newtonsoft.Json.Linq instance type (like `JValue`, `JObject`, `JArray`) will be created depending on the json text,

Dotnetfiddle demonstrating both approaches: https://dotnetfiddle.net/sn42pr

**Comment by LukAss741** [comment]
thanks a lot
