### ISSUE TITLE
How to ignore base class property when serialization?

### ISSUE THREAD

**Issue by GF-Huang** [JamesNK/Newtonsoft.Json#2524]
The base class is third-party class, I can't change it or add any attributes to it.

I can't ask on stackoverflow.

![image](https://user-images.githubusercontent.com/4510984/117441534-193fc000-af68-11eb-8872-4a1bcdb73d4e.png)

**Comment by elgonzo** [comment]
You have basically two approaches (and possibly other but less clean ways):

1. Choose an opt-in model where every property participating in (de)serialization has to be explicitly annotated by an attribute. You can use either attributes provided by Newtonsoft.Json's (see the fist code example here: https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm; note the OptIn parameter on the [JsonObject] attribute). Or, alternatively you can use .NET's own `[DataContract]`/`[DataMember]` attributes if you want to don't want to make your data models dependent on Newtonsoft.Json.

2. Write a custom contract resolver that for (a) given type(s) collects the properties that should participate in (de)serialization. A simple example of that is the code example titled "Conditional properties with IContractResolver" you can find here: https://www.newtonsoft.com/json/help/html/ContractResolver.htm. The obvious difference to that simple example, in your case the condition is not the name of the property but the class in which a property has been declared (i.e. [MemberInfo.DeclaringType](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.declaringtype?view=net-5.0#System_Reflection_MemberInfo_DeclaringType)). And don't forget to set your custom contract resolver in your JsonSerializerSettings (see the very first code example on the page illustrating how to configure the JsonSerializerSettings with a contract resolver)

**Comment by GF-Huang** [comment]
Thanks, the option 2 I think I had implemented: [Json.NET.FlexibleContractResolver](https://github.com/GF-Huang/Json.NET.FlexibleContractResolver). But I think this is still not convenient and concise enough.

**Comment by GF-Huang** [comment]
If the [ShouldSerialize](https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm) able to effect the parent property will be better. For example:

```cs
// Third class, I can't modify it.
class Parent {
    public int Property1 { get; }
}

// My custom class
class MyClass : Parent {
    public int Property2 { get; set; }
    public bool ShouldSerializeProperty1() => false;
}
```

I had try the above, but not works.

**Comment by elgonzo** [comment]
Yeah, this unfortunately does not work directly. The ShouldSerialize* method is a companion method to the property and would have to be declared with the property together in the same type/class.

If you want/need to stick with the ShouldSerialize* approach, you could write a custom contract resolver that is working working around this issue by using reflection to collect the properties and trying to find matching ShouldSerialize* methods regardless of where they are declared in the inheritance chain, but then again, since this would require a custom contract resolver to make it work, you could just simply write the contract resolver withour relying on ShouldSerialize* methods, if you prefer...

**Comment by GF-Huang** [comment]
OK, thanks..
