### ISSUE TITLE
Base class containing property with same name.

### ISSUE THREAD

**Issue by ryanfalzon** [JamesNK/Newtonsoft.Json#2544]
https://stackoverflow.com/q/67920658/7801107

**Comment by elgonzo** [comment]
The problem is due to your contract resolver relying on the DefaultContractResolver collecting the instance properties and calling the CreateProperty override in your DatabaseEntryResolver. Since `B.Id` hides `A.Id` (in case you are not aware, note that member hiding is an entirely different concept from member overriding, and B.Id does **not** override A.Id), the `A.Id` is not part of the properties collected by the logic as implemented by DefaultContractResolver when serializing an object of type `B` (note that your example code given in the StackOverflow question mistakenly uses an instance of `A` instead of `B`)

When serializing an object of type `B`, the only properties collected are `B.Id`, `B.Name`, and `A. CompKey`. Note that `A.Id` is **not** being collected because it is hidden by `B.Id`.

What you need to do (conceptually) in your contract resolver is to additionally override `GetSerializableMembers`, with the  following logic (pseudo-code):

```
    protected override List<MemberInfo> GetSerializableMembers(Type objectType)
    {
        var members = base.GetSerializableMembers(objectType);
        var baseType = objectType.BaseType;
        while (baseType != null)
        {
            var baseMembers = base.GetSerializableMembers(baseType);

            baseMembers = filter baseMembers based on the member being a property or field and such

            members = Union of members and baseMembers -- make sure the same member does not appear multiple times in the members collection

            baseType = baseType.BaseType;
        }

        return members;
    }
```

(P.S.: I don't have a StackOverflow accont nor do i want to create one. So, if you like, and under the assumption my suggestion here helps you solve your problem, you may self-answer your question on Stackoverflow.)

**Comment by elgonzo** [comment]
Why do you have defined the same json property name for both `A.Id` and `B.Id`? Both have an `[JsonProperty("id")]` attribute. That's the crux of the problem.

What's the point of having the same json property name for two different properties (which we have here; just in case you are unaware: note that `B.Id` is hiding `A.Id`. `B.Id` is **not** overriding `A.Id`). Trying to include both properties in the serialization will lead to a json object with duplicate property names. If only one of `A.Id` or `B.Id` should be serialized, one of the two `[JsonProperty("id")]` is unnecessary.

**Comment by ryanfalzon** [comment]
@elgonzo I need both properties as B would be the model that I will be deserializing an HTTP response too and A would be the normalized model between all HTTP responses I receive. Therefore I need both JsonProperty attributes as one will be to deserialize and the other to serialize. Due to the nature of how horrible data is sent, this is our only approach. However, your response prior to the edit did the trick! So thanks a lot.

**Comment by elgonzo** [comment]
My apologies for deleting my original post, which i deleted when i suddenly noticed that there are two "id" json properties and i went like "wait a minute... does that really make sense?" Still, i am glad you saw it and it helped you before i deleted it. Now i wish i could bring my original post back, but it seems to be gone for good. :(

**Comment by ryanfalzon** [comment]
@elgonzo good thing I have e-mail notifications turned on. For the benefit of everyone who has the same problem:

> The problem is due to your contract resolver relying on the DefaultContractResolver collecting the instance properties and calling the CreateProperty override in your DatabaseEntryResolver. Since B.Id hides A.Id (in case you are not aware, note that member hiding is an entirely different concept from member overriding, and B.Id does not override A.Id), the A.Id is not part of the properties collected by the logic as implemented by DefaultContractResolver when serializing an object of type B (note that your example code given in the StackOverflow question mistakenly uses an instance of A instead of B)
> When serializing an object of type B, the only properties collected are B.Id, B.Name, and A. CompKey. Note that A.Id is not being collected because it is hidden by B.Id.

> What you need to do (conceptually) in your contract resolver is to additionally override GetSerializableMembers, with the following logic (pseudo-code):

```csharp
protected override List<MemberInfo> GetSerializableMembers(Type objectType)
{
	var members = base.GetSerializableMembers(objectType);
	var baseType = objectType.BaseType;
	while (baseType != null)
	{
		var baseMembers = base.GetSerializableMembers(baseType);

		baseMembers = filter baseMembers based on the member being a property or field and such

		members = Union of members and baseMembers -- make sure the same member does not appear multiple times in the members collection

		baseType = baseType.BaseType;
	}

	return members;
}
```
