### ISSUE TITLE
How arabic content support in JsonConvert.SerializeObject

### ISSUE THREAD

**Issue by rashidbilgrami** [JamesNK/Newtonsoft.Json#2564]
Hi, 
When I tried to serialize the data table with Arabic content the return result with Arabic content came with crap. can you please inform me how can I fix it? 

Below is a result if you checked out the example the utf-8 characters are not supporting, the DB is returning the data correctly. 

 {"Question_Title":"Q01 MR Test G1","Question_Description":"
\"\"

\n","Subject_CategoryName":"Mechanical","isAnalytical":false,"Question_Type":1,"isAuto_generatedQuestions":false,"Given_answerOption":null,"Correct_answerOption":null,"examTitle":"ØªØ¬Ø±Ø¨Ø© 6 (Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ø£ÙˆÙ„Ù‰)","examDate":"2021-07-01T00:00:00","examStart_time":"12:30:00","examEnd_time":"13:00:00","FinishExam":true},

Lookinf forward for your reply

**Comment by elgonzo** [comment]
Not confirmed. No crap to be found.

It looks like you just made a mistake when inspecting the json text. Note that the json data itself is encoded in UTF-8, therefore it has to be read/deserialized using UTF-8 encoding.

Your result of `ØªØ¬Ø±Ø¨Ø© 6 (Ø§Ù„Ù…Ø¬Ù…ÙˆØ¹Ø© Ø§Ù„Ø£ÙˆÙ„Ù‰)` clearly shows that you used something that incorrectly reads (or converts) the json text as ANSI instead of UTF-8.

By the way, i am not just making a wild guess here. I can tell that the original arabic text is `تجربة 6 (المجموعة الأولى)`, and what you saw in your observation is simply the UTF-8 code points of this arabic text if it is incorrectly read/interpreted with some ANSI encoding.

**Comment by rashidbilgrami** [comment]
Hi thanks for the reply, actually I got it there was no issue its because of viewing directly on browser
