### ISSUE TITLE
cast JValue "as" nullable valuetype does not work

### ISSUE THREAD

**Issue by alex-jitbit** [JamesNK/Newtonsoft.Json#2586]
version 13.0.1, running in NET 5 (Core)

### Steps to reproduce

```csharp
dynamic x = Newtonsoft.Json.Linq.JArray.Parse("[ { \"test\": true } ]");
var x1 = (bool)x[0].test; //works - "true"
var x2 = Convert.ToBoolean(x[0].test); //works - "true"
var x3 = x[0].test as bool?; //returns null !!!!
```

**Comment by alex-jitbit** [comment]
Same with `int?`

**Comment by elgonzo** [comment]
This is not an issue with Newtonsoft.Json, but you misunderstand how the `as` operator works.

Look at the documentation for the [`as` operator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#as-operator):

> The expression of the form `E as T` where E is an expression that returns a value and T is the name of a type or a type parameter, produces the same result as **_`E is T ? (T)(E) : (T)null`_** except that E is only evaluated once.
>
> The as operator considers only reference, nullable, boxing, and unboxing conversions. **_You cannot use the as operator to perform a user-defined conversion_**. To do that, use a cast expression.
(Emphasis mine)

Thus, as the C# language doc suggest, use a cast operator in this case, like you did with x1.

(By the way, JToken - and thus JValue - do have a `bool?` conversion operator)

**Comment by alex-jitbit** [comment]
Well, same code worked fine under 12.0.3.

And I just tested with this code, works as it should:

```csharp
dynamic x = true;
x as bool? //returns true;
```

It's only when Newtons

**Comment by elgonzo** [comment]
Well, if you like to disagree with the language specification, you are free to do that. You are even free to claim that you had code running under 12.0.3 that seemingly proved the language specification wrong. Why not...
```C#
dynamic x = true;
```
is a red herring. Converting a `bool` to `bool?` does not require a user-defined conversion operator...

**Comment by alex-jitbit** [comment]
Nope, my code does not conflict with the language specification, but enough of that.. Forget the `as` operator already.

`x is bool?` should resolve to `true` if `x` is a boolean. Period.

Consider this repro

```csharp
dynamic x = Newtonsoft.Json.Linq.JArray.Parse("[ { \"test\": true } ]");
var result = x[0].test is bool?; //FALSE - why?

bool test = true;
result = test is bool?; //TRUE - correct
```

**Comment by elgonzo** [comment]
Wait? We are not talking about the `as` operator anymore? I would have no problem with that, but your entire issue report here is based on the behavior of the `as` operator, not the `is` operator. Wouldn't it be a better approach to close this issue here, and move the discussion over to, for example, StackOverflow.com, or some other programming-related Q&A site?

```C#
result = x[0].test is bool?; //FALSE - why?
```
because `x[0].test` is neither a `bool` nor a `bool?`, obviously. It is a `JValue` instance, you know this already...

**Comment by alex-jitbit** [comment]
I just converted the repro project to Newtonsoft 12.0.3 and net472 and voi-la

`result = x[0].test is bool?; //TRUE`

back to net5 and Newtonsoft 13.0.1

`result = x[0].test is bool?; //FALSE`

**Comment by elgonzo** [comment]
I believe there is something else going on with your code that depends on the build target framework.
Instead of `result = x[0].test is bool?;` check the runtime type of `x[0].test` like `x[0].test.GetType().FullName` and see whether you get different runtime types between running 12.0.3/net472 and 13.0.1/.net5...

**Comment by elgonzo** [comment]
I just ran your example with `is` on dotnetfiddle under .NET 4.7.2 with Newtonsoft.Json 12.0.3. See for yourself: https://dotnetfiddle.net/WZ6ly5

**Comment by alex-jitbit** [comment]
Confirming dotnetfiddle works as described,, I'll recheck my test project and get back
