### ISSUE TITLE
Can't read Json with a list called "Sets" - Error "Unexpected character encountered while parsing value"

### ISSUE THREAD

**Issue by MatthiasBae** [JamesNK/Newtonsoft.Json#2592]
Hello all,

I have a problem with Populating a class from a Json. Before this, I created this JSON without any problems with the exact same class i want to re-populate.

The error I get is: Newtonsoft.Json.JsonReaderException: "Unexpected character encountered while parsing value: [. Path 'Sessions[0].Workouts[0].Excercises[0].Sets', line 20, position 23."

I have a list of classes ![grafik](https://user-images.githubusercontent.com/52577744/136384324-fdd98b7d-216a-46c4-9ba7-ad83a0cd8b3b.png)
 and it seems that the reader has a problem with the word "Sets" as list variable name. When i rename it to "Setz" or "Setss" or something else, everything works fine.
This is my JSON
![grafik](https://user-images.githubusercontent.com/52577744/136383328-d58a5b8e-863a-43aa-83e8-1233be83703d.png)

This is the part of the class
![grafik](https://user-images.githubusercontent.com/52577744/136383446-ce605012-f914-443a-bac6-6876b2098e46.png)

The code fails here
![grafik](https://user-images.githubusercontent.com/52577744/136383570-31b2a4be-7855-411e-b672-b3e84053d7e6.png)

**Comment by elgonzo** [comment]
Alright. I know _what_ causes the problem, but i do not really know _why_... (as of now).

Your `TrainingExercise` class has a constructor with an `int sets` argument. Changing the name of this constructor argument (for example to `int numberOfSets`) will solve the issue. Changing the name "Sets" of the public field to something else will not solve the issue, however. (In your report you mentioned the field variable "Sets" which i assumed you were referring to the field name "Sets" itself not the constructor argument name. But maybe i was misunderstanding your explanation there...) 

This is how i imagine the problem manifests: As Newtonsoft.Json has to create _TrainingExercise_ instances, it has to invoke the constructor with values for each constructor argument. It tries to do so by mapping each constructor argument with the value of a Json property (of the respective Json object) with a (case-insensitive) matching name. According to the constructor argument "sets", Newtonsoft.Json looks in the _TrainingExercise_ Json object for an the "Sets" property, and finds it. And then proceeds to attempting to read/parse an integer value, but finds a Json array instead.

But there is a "But". I big one... I said "_this is how imagine_" with a reason. Which totally confuses me, and which is also why i wrote in the beginning that i don't know why it happens.

When reading your report, i already had a hunch it might be the constructor argument `int sets`. That's why i included a constructor with a `int sets` argument in my dotnetfiddle as well. But my dotnetfiddle does not fail, which is why i discarded my hunch. And this is also why i do not entirely trust my imagination here. I still have no clue of _why_ your code is throwing when the argument name in the _TrainingExercise_ constructor is `int sets` whereas my dotnetfiddle is not throwing. Hmm, puzzling... perhaps it might require a certain depth of nested Json objects to be triggered, perhaps it might be something else. As of now i have no solid idea, though...
