### ISSUE TITLE
Error CS1705: which has a higher version than referenced assembly 'Newtonsoft.Json'

### ISSUE THREAD

**Issue by kelicto** [JamesNK/Newtonsoft.Json#2640]
![image](https://user-images.githubusercontent.com/23723575/149905070-b91f6b95-fe9b-413e-94f9-73bf560bacb0.png)
![image](https://user-images.githubusercontent.com/23723575/149905581-6672a6ca-971d-4056-94a8-7c319400ddd5.png)
![image](https://user-images.githubusercontent.com/23723575/149906543-63a5737c-7881-4602-91ae-ef43c0f5e871.png)

When I print the value of one JArray variable:
error CS1705: Assembly 'Ds.EpDesign.Revit.UI' with identity 'Ds.EpDesign.Revit.UI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' which has a higher version than referenced assembly 'Newtonsoft.Json' with identity 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'

**Comment by elgonzo** [comment]
Clean the build folders.
Remove the Newtonsoft.Json refereces from the projects in your VS solution, then add Newtonsoft.Json back to all those projects in your VS solutions that requires it, making sure each is referencing the same package version (13.0.1).
Restart VS.

This might or might not help, but i believe the problem being something wrt to your projects (i.e., perhaps you have multiple projects in your solution, some of which referencing different Newtonsoft.Json versions, with the "older" Newtonsoft.Json version from one of those projects "surviving" in the build folder of your executable main project).

I don't think the problem is with Newtonsoft.Json itself. I just checked the 13.0.1 nuget package, and the Newtonsoft.Json net45 DLL that should be used for net48 targets is correctly versioned as 13.0.0.0.

**Comment by kelicto** [comment]
I can only get the value of 'JToken' or 'JArray' variable through 'Debug Write() ', but you can't view the variable value. And as you said, I have tested that the stand-alone demo works normally. I this is a Revit plug-in project, which adds a lot of complexity. I will actively check the problem, thank you.

**Comment by elgonzo** [comment]
If you are writing a plug-in that runs in an execution context or application domain set-up by Revit, I strongly suggest to consult the Revit manual (if there is any) or to visit some Revit-specifc forums that discusses development of Revit plug-ins, and see if there is any talking about using Newtonsoft.Json in a plug-in. It could be that Revit itself (or Revit's plug-in infrastructure) depend and has loaded Newtonsoft.Json 11.0.0.1 for your plug-in.

**Comment by kelicto** [comment]
I found that is referenced in the main program, I used it and found new problems.
![image](https://user-images.githubusercontent.com/23723575/150245071-aa49c59b-63c1-4872-b395-a8e3ac029059.png)
![image](https://user-images.githubusercontent.com/23723575/150244941-9eb85a32-fee0-4917-a3e3-92f5be3ff7bd.png)
![image](https://user-images.githubusercontent.com/23723575/150244748-8c8cda1b-ce63-4922-974e-87592cd252c1.png)

**Comment by kelicto** [comment]
Nice, it's ok now. But, I seem to have found a vs problem. I can't observe the value of case variable. I need a new experiment.
![image](https://user-images.githubusercontent.com/23723575/150248902-cc6a96fd-a96f-4f14-b1ea-2bbedbc937ca.png)
