### ISSUE TITLE
UnixDateTimeConverter throws "Value to add was out of range" exception

### ISSUE THREAD

**Issue by mwinkler** [JamesNK/Newtonsoft.Json#2644]
Hi

`UnixDateTimeConverter` throws `Value to add was out of range. (Parameter 'value')` exception,
when deserialize Unix time stamp 1642063192000 (Thu Jan 13 2022 08:39:52 GMT+0000)

Example (.NET 6, Json.net 13.0.1)

```csharp
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


var data = JsonConvert.DeserializeObject<Data>("{\"Date\":1642063192000}");

class Data
{
    [JsonConverter(typeof(UnixDateTimeConverter))]
    public DateTime Date { get; set; }
}
```

**Comment by elgonzo** [comment]
Well, [Unix Epoch time](https://en.wikipedia.org/wiki/Unix_time) is traditionally given in seconds. And that's what _UnixDateTimeConverter_ does: treating numbers as Unix Epoch time given in _seconds_.

However, here you got a _millisecond_ timestamp. The exception is just the side effect of the number being treated and added as seconds to Unix epoch, and thus exceeding DateTime.MaxValue.

Unfortunately, _UnixDateTimeConverter_ can't be configured to accept millisecond timestamp values.

To support millisecond timestamps, i would suggest writing your own converter. The implementation should be rather simple and straightforward (you could use UnixDateTimeConverter's source code as a template for your own implementation).

<BR>

That _UnixDateTimeConverter_ just throws the _ArgumentOutOfRangeException_ without actually providing information about which part of the Json input caused the issue is still something that needs improvement in my opinion.

**Comment by mwinkler** [comment]
Hi @elgonzo, thank you very much for the hint!
Didn't recognize that the timestamp was in millisecond.
Now it seems logical due a 'long' overflow.
I will implement my own converter.

**Comment by NoofSaeidh** [comment]
Isn't it possible to provide a converter that uses milliseconds from out the box?
It is required often.
