### ISSUE TITLE
Deserialize of Dicionary will get wrong result / exception if key is $id when the value is / not a simple type

### ISSUE THREAD

**Issue by JiaHenry** [JamesNK/Newtonsoft.Json#2646]
### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
public class User
    {
        public string name { get; set; }
        public int age { get; set; }
    }    
```

### Source/destination JSON

```javascript
{"$id":{"name":"Hello","age":26},"value":{"name":"Hello2","age":28}}
```

### Expected behavior

Dictionary<string, User>

### Actual behavior

Newtonsoft.Json.JsonSerializationException: 'Error converting value "Hello" to type '****.User'. Path '$id.name', line 1, position 22.'

### Steps to reproduce

```csharp
    public class User
    {
        public string name { get; set; }
        public int age { get; set; }

        public static void ShowIssue()
        {
            var dic = new Dictionary<string, User> {
                {"$id", new User() { name = "Hello", age = 26 } },
                {"value", new User() { name = "Hello2", age = 28 } },
            };

            var str = JsonConvert.SerializeObject(dic);
            Console.WriteLine(str);

            var dic2 = JsonConvert.DeserializeObject<Dictionary<string, User>>(str);
            Console.WriteLine(string.Join(", ", dic2.Keys.ToArray()));
        }

        public static void NoIssue()
        {
            var dic = new Dictionary<string, User> {
                {"$value", new User() { name = "Hello", age = 26 } },
                {"value", new User() { name = "Hello2", age = 28 } },
            };

            var str = JsonConvert.SerializeObject(dic);
            Console.WriteLine(str);

            var dic2 = JsonConvert.DeserializeObject<Dictionary<string, User>>(str);
            Console.WriteLine(string.Join(", ", dic2.Keys.ToArray()));
        }

        public static void MissingKey()
        {
            var dic = new Dictionary<string, int> {
                {"$id", 26 },
                {"value",  28 },
            };

            var str = JsonConvert.SerializeObject(dic);
            Console.WriteLine(str);

            var dic2 = JsonConvert.DeserializeObject<Dictionary<string, int>>(str);
            Console.WriteLine(string.Join(", ", dic2.Keys.ToArray()));
        }
    }
```
User.NoIssue();  // this one is fine
User.MissingKey(); // the $id is missing and only returned key "value"
User.ShowIssue();  // will get exception as above

**Comment by elgonzo** [comment]
That's because $id clashes with the metadata keyword `$id`. Newtonsoft.Json recognizes this (and other metadata keywords) by default when deserializing json.

As you noticed, this can be a problem when you construct Json objects which has property names that match those metadata keywords but should be rather ordinary properties.

In cases such as this where the property names in constructed Json objects are or cannot be explicitly controlled and defined, recognition of metadata keywords such as `$id` can be disabled, effectively turning them into ordinary property names.

To disable the metadata keyword recognition, set the `JsonSerializerSettings.MetadataPropertyHandling` property to [`MetadataPropertyHandling.Ignore`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_MetadataPropertyHandling.htm), for example like this:
```C#
var serializationSettings = new JsonSerializerSettings
{
    MetadataPropertyHandling = MetadataPropertyHandling.Ignore
};
		
JsonConvert.DefaultSettings = () => serializationSettings;```
```

dotnetfiddle demo using your example code from above: https://dotnetfiddle.net/cyDlnZ

**Comment by JiaHenry** [comment]
Thanks for your quick reply.
