### ISSUE TITLE
JObject's "Remove" function does not actually remove anything

### ISSUE THREAD

**Issue by zaneclaes** [JamesNK/Newtonsoft.Json#2653]
### Source/destination types

```csharp
public class BossBattlePlayer  {
    public string Id { get; set; } = default!;
}
```

### Source/destination JSON

```javascript
{
  "__typename": "BossBattlePlayer",
  "id": "a796e8e7-f52c-43e7-be9c-0165d4b11da5"
}
```

### Expected behavior

Upon calling `Remove()`, the key should be removed from the JObject.

### Actual behavior

No keys are removed, even though the function returns `true`. 

The internal `_properties` variable is never updated because [the Remove function does not even attempt to do so](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Linq/JObject.cs#L594-L609).  

### Steps to reproduce

Assuming `strData` is set to the JSON above...

```csharp
JObject data = JObject.Parse(strData);
bool removed = data.Remove("__typename"); // true

bool actuallyRemoved = !data.DeepEquals(JObject.Parse(strData)); // false
bool actuallyRemoved1 = data.Property("__typename") == null; // false
bool actuallyRemoved2 = !data.ToString().Equals(strData); // false
```

As the last lines demonstrate, none of the functions behave as if the data has been properly removed.

Moreover, attempts to cast the `JObject` into the destination type fail:
`JsonConvert.DeserializeObject<BossBattlePlayer>(data.ToString());` yields:

```
ArgumentException:  cannot be cast to BossBattlePlayer
Networking.WebRequestExtensions.ToResponseObject[TData] (UnityEngine.Networking.UnityWebRequest request, System.String key) (at Assets/Scripts/Networking/WebRequestExtensions.cs:43)
Networking.FurballsApi+<ExecuteAsync>d__17`1[TResponse].MoveNext () (at Assets/Scripts/Networking/FurballsApi.cs:78)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@50a67d8f41/Runtime/CompilerServices/StateMachineRunner.cs:342)
Networking.FurballsApi+<StartGameLoop>d__14.MoveNext () (at Assets/Scripts/Networking/FurballsApi.cs:42)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTask`2[TStateMachine,T].GetResult (System.Int16 token) (at Library/PackageCache/com.cysharp.unitask@50a67d8f41/Runtime/CompilerServices/StateMachineRunner.cs:342)
StateSetUp+<Enter>d__4.MoveNext () (at Assets/Scripts/Gameplay/BossBattle/StateSetUp.cs:39)
--- End of stack trace from previous location where exception was thrown —-
```

Note that manually removing `__typename` from the JSON does allow the object to be successfully cast.

**Comment by elgonzo** [comment]
I cannot reproduce with Newtonsoft.Json 13.0.1. Proof: https://dotnetfiddle.net/sVLle2

Try updating your Newtonsoft.Json library to the latest official release 13.0.1 from the author of the library ([nuget](https://www.nuget.org/packages/Newtonsoft.Json)).

Also, your sample code is using the `DeepEquals` method like an instance method or extension method.
But `DeepEquals` is neither an instance nor an extension method -- it is a simple [static method](https://www.newtonsoft.com/json/help/html/M_Newtonsoft_Json_Linq_JToken_DeepEquals.htm). I checked back as far as Newtonsoft 9.0.1 and _DeepEquals_ is still a simple static method in this old version. Is this perhaps an indication that you are not using an offical Newtonsoft.Json library, but some modified library build made and provided by a 3rd party (and not from the author of the library)? If so, make sure you are using only official builds of the Newtonsoft.Json library provided directly by the author of the library, JamesNK.

**Comment by elgonzo** [comment]
An addendum wrg to your claim of "_The internal \_properties variable is never updated because [...]".

This claim is is incorrect. If you look at the method you linked to:

https://github.com/JamesNK/Newtonsoft.Json/blob/52190a3a3de6ef9a556583cbcb2381073e7197bc/Src/Newtonsoft.Json/Linq/JObject.cs#L599-L609

Note that `property.Remove()` is called. This method is implemented by JToken (which JProperty derives from):

https://github.com/JamesNK/Newtonsoft.Json/blob/52190a3a3de6ef9a556583cbcb2381073e7197bc/Src/Newtonsoft.Json/Linq/JToken.cs#L390-L398

Note that this method in turn calls `_parent.RemoveItem(this);`, an instance method of the JObject instance containing the property, and which is implemented by JContainer (which JObject derives from):

https://github.com/JamesNK/Newtonsoft.Json/blob/52190a3a3de6ef9a556583cbcb2381073e7197bc/Src/Newtonsoft.Json/Linq/JContainer.cs#L451-L464

This in turn calls `RemoveItemAt(index);`:

https://github.com/JamesNK/Newtonsoft.Json/blob/52190a3a3de6ef9a556583cbcb2381073e7197bc/Src/Newtonsoft.Json/Linq/JContainer.cs#L403-L435

The relevant excerpt of this method is:
```C#
IList<JToken> children = ChildrenTokens;
...
children.RemoveAt(index);
```
So, what is this `ChildrenTokens` field/property?

https://github.com/JamesNK/Newtonsoft.Json/blob/52190a3a3de6ef9a556583cbcb2381073e7197bc/Src/Newtonsoft.Json/Linq/JObject.cs#L66-L70

Bingo!

**Comment by zaneclaes** [comment]
> So, what is this ChildrenTokens field/property?

Ah-hah, I had made it up to this step, except missed the override.

> I cannot reproduce with Newtonsoft.Json 13.0.1. Proof: https://dotnetfiddle.net/EYIgjo

Thanks for that. After digging deeper, it appears that my project had a namespace collision around `BossBattlePlayer` (due to another project auto-generating code). When the deserialization failed and an exception was thrown, my log statements were outside the exception block in a way that made it appear that there was a bug when there was not.

Again, thanks for the deep dive. I knew it was unlikely that such a battle-tested library would have such a bug, but the way in which **my** test code was bugged was very non-obvious (it's almost identical to yours, plus a try/catch).
