### ISSUE TITLE
Using JsonConvert in Equals will cause stack overflow

### ISSUE THREAD

**Issue by Kimi-Arthur** [JamesNK/Newtonsoft.Json#2656]
### Source/destination types

```csharp
public class Node {
    public string Id { get; set; }
    public List<Node> Children { get; set; }

    public override string ToString() => JsonConvert.SerializeObject(this);

    public override int GetHashCode() => ToString().GetHashCode();

    public override bool Equals(object? obj)
        => GetType().IsInstanceOfType(obj) && ToString() == obj?.ToString();
}
```

### Source/destination JSON

```javascript
{"Id":"1","Children":[{"Id":"2","Children":null},{"Id":"3","Children":null}]}
```

### Expected behavior

Serialize and deserialize successfully.

### Actual behavior

Stack overflow

### Steps to reproduce

```csharp
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Kifa.Experiments;

public class Node {
    public string Id { get; set; }
    public List<Node> Children { get; set; }

    public override string ToString() => JsonConvert.SerializeObject(this);

    public override int GetHashCode() => ToString().GetHashCode();

    public override bool Equals(object? obj)
        => GetType().IsInstanceOfType(obj) && ToString() == obj?.ToString();
}

class Program {
    static void Main(string[] args) {
        var a = new Node {
            Id = "1",
            Children = new List<Node> {
                new Node {
                    Id = "2"
                },
                new Node {
                    Id = "3"
                }
            }
        };

        Console.WriteLine(JsonConvert.SerializeObject(a));
    }
}

```

**Comment by bartelink** [comment]
I'd suggest closing this issues and asking it on stackoverflow.com - its not at this point proven that the issue is something that's specific to this library

**Comment by Kimi-Arthur** [comment]
This is happening in `JsonSerializerInternalWriter.CheckForCircularReference()`. Maybe Json.net can work around this by using reference check? It should only care that two objects are the same reference instead of whether the two values are the same (which is defined by `Equals()` and used by `List.contains()`).

<img width="722" alt="Screen Shot 2022-03-25 at 17 03 46" src="https://user-images.githubusercontent.com/2446305/160157675-6ce4f44d-244a-40b4-9278-9a41d6e2f5f6.png">


BTW, from my understanding, for the two cases [here](https://github.com/JamesNK/Newtonsoft.Json/blob/f7e7bd05d9280f17993500085202ff4ea150564a/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs#L348-L361), you don't even need to check references at all, which will also save some computation time if `Equals()` is heavy.

For that, I should code like below, but it still breaks for now:

```csharp
using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Kifa.Experiments;

public class Node {
    public string Id { get; set; }
    public List<Node> Children { get; set; }

    public override string ToString()
        => JsonConvert.SerializeObject(this, new JsonSerializerSettings {
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore
        });

    public override int GetHashCode() => ToString().GetHashCode();

    public override bool Equals(object? obj)
        => GetType().IsInstanceOfType(obj) && ToString() == obj?.ToString();
}

class Program {
    static void Main(string[] args) {
        var a = new Node {
            Id = "1",
            Children = new List<Node> {
                new Node {
                    Id = "2"
                },
                new Node {
                    Id = "3"
                }
            }
        };

        Console.WriteLine(JsonConvert.SerializeObject(a, new JsonSerializerSettings {
            ReferenceLoopHandling = ReferenceLoopHandling.Ignore
        }));
    }
}
```

**Comment by elgonzo** [comment]
This is not a bug. Using equality comparison for detecting circular references is intended default behavior. For example, see this comment from the author of the library: https://github.com/JamesNK/Newtonsoft.Json/issues/401#issuecomment-77711185. (Mostly because this behavior has already been established over a span of numerious library versions across many years before people started asking for a change of this behavior. But at that point breaking compatibility by breaking established default behavior was deemed not acceptable anymore. Unfortunate, but understandable and reasonable...)

I understand that the default behavior of Newtonsoft.Json is colliding with your specific implementation of the Equals method, but that's not a bug in the library, that's just a bad coincidence.

Fortunately for you (and others wanting to only use reference comparisons), Newtonsoft.Json's behavior can be changed in this regard by setting `JsonSerializerSettings.EqualityComparer` accordingly:
```C#
new JsonSerializerSettings
{
    ...
    EqualityComparer = ReferenceEqualityComparer.Instance
};
```
Try this and see whether it resolves your issue...

**Comment by Kimi-Arthur** [comment]
I see. It did work around my problem.

But do you really think the original code should break? Nothing obvious should alert you that stack overflow can happen (it didn't even ask for circular check) + even if you specify no circular check is needed (`ReferenceLoopHandling.Serialize`), it still won't work.

**Comment by elgonzo** [comment]
> But do you really think the original code should break?

Absolutely yes. Because of how you implemented the Equals method -- _you_ (not the library!) essentially programmed infinite recursion here. It is not the job of the library to work around your particular Equals implementation.

However, where i put blame on the library -- or rather its documentation -- is that it poorly documents the default "out of the box" behavior. 

While the documentation is [explaining the use of Equals and the default ReferenceLoopHandling mode being Error](https://www.newtonsoft.com/json/help/html/SerializationSettings.htm#ReferenceLoopHandling) (with the Error mode obviously requiring reference checks to be able to detect circular references), it could make a _much_ better job in explaining the library's "out of the box" default behavior. A user of the library will be unaware of this unless they specifically look for this or come across it by chance when perusing the documentation (and then would still demand the reader to make the context switch from "references" as in ".NET object references" to the different meaning of how Newtonsoft.Json uses the term "references" as to not get confused by the documentation).

Running into a problem with the library like yours should ideally be answerable with "RTFM", but regrettably, Newtonsoft.Json's documentation is not one of its strengths, in my opinion :-( (I still love the library due to its versatility. But my love of the library does not extends to its documentation, sadly.)

**Comment by Kimi-Arthur** [comment]
I'm just frustrated that 1) `JsonConvert.SerializeObject()` will call `Equals()` and 2) `ReferenceLoopHandling.Serialize` still does partly relies reference loops, which it defiftely can skip even for performance gain. Both are quite unintuitive...

But thanks for your workaround anyway.
