### ISSUE TITLE
ReferenceLoopHandling.Ignore not working properly

### ISSUE THREAD

**Issue by MasoudShah** [JamesNK/Newtonsoft.Json#2665]
Let's say I have two tables in my database with one-to-many relation like this:
```
public class ProductType
{
    [Key]
    public int Id { get; set; }

    public virtual ICollection<Product> Products{ get; set; }
}
public class Product
{
    [Key]
    public int Id { get; set; }

    [ForeignKey(nameof(ProductType))]
    public int ProductTypeId { get; set; }

    public virtual ProductType ProductType { get; set; }
}
```
What I want to do is to query some products including their `ProductType` so the server response is an array of `Product`. I also enabled the ignore reference loop in json that server returns using the code below:
```
...
options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
...
```
But there is an unwanted behavior. What I'm facing is an array of products including their `ProductType` and inside each `ProductType`, I expect it to have null or empty array of products (or no array of products at all), but the array is not empty. Inside the `Products` array, there are all the products that server has returned in the first level, except the one that the `ProductType` itself is inside. For better understanding the result is like below:
```
[
    {
        "id": 1,
        "productTypeId": 1,
        "productType": {
            "id": 1,
            "products": [
                {
                    "id": 2
                },
                {
                    "id": 3
                }
            ]
        }
    },
    {
        "id": 2,
        "productTypeId": 1,
        "productType": {
            "id": 1,
            "products": [
                {
                    "id": 1
                },
                {
                    "id": 3
                }
            ]
        }
    },
    {
        "id": 3,
        "productTypeId": 1,
        "productType": {
            "id": 1,
            "products": [
                {
                    "id": 1
                },
                {
                    "id": 2
                }
            ]
        }
    }
]
```
I don't know it is a bug or normal behavior, but how can I avoid loading the first level objects (products) in the third level? If ignoring reference loop cannot do that job, is there any straight workaround without using view models?

**Comment by MasoudShah** [comment]
Sorry for vagueness. It is the json I get from the server. I need a different one that inside each `productType` there would be a null or empty or even absent array of `products`. The expected json I want to achieve is something like this:
```
[
    {
        "id": 1,
        "productTypeId": 1,
        "productType": {
            "id": 1
        }
    },
    {
        "id": 2,
        "productTypeId": 1,
        "productType": {
            "id": 1
        }
    },
    {
        "id": 3,
        "productTypeId": 1,
        "productType": {
            "id": 1
        }
    }
]
```
The reason I want such a structure, is that the main array in the first level is a bunch of products and these products shouldn't get serialized repeatedly in each `productType` who are inside the products themselves. I got query from `products` table and included only `productType`, so I don't expect the products array inside each `productType` again. I wish my concern was clear.

**Comment by elgonzo** [comment]
If i understand you correctly, you want to ignore the _ProductType.Products_ property from serialization.[^1] 

There are a number of different ways to exclude type members such as _ProductType.Products_ from serialization.

The first and simplest way is attribute-based. Newtonsoft.Json offers a number of attributes to either either explicitly exclude/ignore certain properties from being serialized (opt-out), or explictly define which properties should partake in serialization (opt-in). 

If you don't like to make your data types/classes dependent on Newtonsoft.Json attributes, Newtonsoft.Json also supports certain attributes from the .NET base class libary (like DataContract/DataMember), for example.

For an overview of what the supported attributes are, see the documentation: https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm

In the simplest case, your _ProductType_ class could be like this:
```#C
public class ProductType
{
    [Key]
    public int Id { get; set; }

    [JsonIgnore]        <=============== note this
    public virtual ICollection<Product> Products{ get; set; }
}
```

There are other ways to exclude the _ProductType.Products_, like defining a [_ShouldSerialize*_ method](https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm), although the attribute-based approach would be simpler for a non-conditional exclusion of _ProductType.Products_.

If you can't or don't want to modify your _ProductType_ class, you could also write a custom ContractResolver that excludes the  _ProductType.Products_ from serialization. An example of how to do that can be found in the documentation: https://www.newtonsoft.com/json/help/html/ConditionalProperties.htm#ID0EAAABAAA_tab1 (it's the example titled "_Conditional properties with IContractResolver_"). Basically, for your situation, such a contract resolver could perhaps boil down to:
```C#
public class NoProductsInProductTypeContractResolver : DefaultContractResolver
{
    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
    {
        JsonProperty property = base.CreateProperty(member, memberSerialization);

        if (property.DeclaringType == typeof(ProductType) && property.PropertyName == nameof(ProductType.Products))
        {
            property.Ignored = true;
        }

        return property;
    }
}
```

[^1]: If that's the case, no wonder ReferenceLoopHandling won't help you here. The setting is not about whether an object is referenced by more than one other object or about some other arbitrary relationships between objects, but specifically about reference loops (in other words circular object graphs). If you look at the serialized result you got, you'll notice that the serializer omitted (i.e., the "ignore" part in _ReferenceLoopHandling.Ignore_) serializing _only_ those objects that would complete/close a circular loop that would otherwise lead to "infinite" recursion (which would in actuality not be infinite but end with either a stack overflow or an out of memory error during serialization).

**Comment by MasoudShah** [comment]
Thanks for the complete answer. It helped me understand how the ReferenceLoopHandling settings work.
