### ISSUE TITLE
JsonConvert.DeserializeObject output wrong value

### ISSUE THREAD

**Issue by b1b2b3b4b5b6** [JamesNK/Newtonsoft.Json#2693]
### Source/destination types

```csharp
  public class Child : Father
  {
      public Child(string id) : base()
      {
      }
  }
  public class Father
  {
      public string id;
      public Father()
      {
          this.id = Guid.NewGuid().ToString("N");
      }
  }
```

### Source/destination JSON
Source Json
```csharp
JsonConvert.SerializeObject(new Child("hello"));
```

### Expected behavior

**obj.id** should equal with the **id** in the src json.

### Actual behavior
Output shows not equal.
```
{"id":"70203818954245029758c6b55bf3865c"}
3dd3c5425e14458e8bf5151209a0d145
```

### Steps to reproduce

```csharp
var src = JsonConvert.SerializeObject(new Child("hello"));
Console.WriteLine(src);
var obj = JsonConvert.DeserializeObject<Child>(src);
Console.WriteLine(obj.id);
```

**Comment by elgonzo** [comment]
This is not a bug. This is the expected behavior.

Newtonsoft.Json uses the `public Child(string id)` constructor during deserialization, passing the _id_ from the json data to the constructor parameter _id_. And your `public Child(string id)` constructor simply ignores/discards the argument value for _id_, so the _Father.id_ field remains as set by `Guid.NewGuid().ToString("N");`.

**Comment by b1b2b3b4b5b6** [comment]
Get it. Thanks you
