### ISSUE TITLE
Add some extra values 

### ISSUE THREAD

**Issue by xutongqing** [JamesNK/Newtonsoft.Json#2712]
### Source/destination types

    public class TestModel
    {
        public List<string> TestPaths { get; set; } = new() { "/test" };
        public string TestName { get; set; }
        public List<string> ListIds { get; set; }
    }

        static void Main(string[] args)
        {
            string test = "{\"TestPaths\":[\"/test\"],\"TestName\":null,\"ListIds\":[\"com.tencent.qqmusic\"]}";
            var testModel = JsonConvert.DeserializeObject<TestModel>(test, new JsonSerializerSettings
            {
                DefaultValueHandling = DefaultValueHandling.Ignore,
            });
            Console.WriteLine("Hello, World!");
        }

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Expected behavior

I just only want 1 TestPaths

### Actual behavior

2 TestPaths

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```
version 13.0.1

**Comment by elgonzo** [comment]
The observed behavior is the intentional default behavior of Newtonsoft.Json. See also the comments here: https://github.com/JamesNK/Newtonsoft.Json/issues/2706

If you want the `List<string>TestPaths` collection being entirely replaced with the values from the json source only, set Newtonsoft.Json's [ObjectCreationHandling setting](https://www.newtonsoft.com/json/help/html/SerializationSettings.htm#ObjectCreationHandling) to `ObjectCreationHandling.Replace`.

**Comment by xutongqing** [comment]
thanks
