### ISSUE TITLE
Deserialise a list with default value, get a combined list.

### ISSUE THREAD

**Issue by rere43** [JamesNK/Newtonsoft.Json#2729]
### Source/destination types
```csharp
// Put the types you are serializing or deserializing here
```
public class Unit
{
    EquipSet equipSet=new();
}
public class EquipSet
{
    List<int> equipID=new (){-1,-1,-1};
}
somewhere else
equipID[0]=4;

serialise the equipSet of Unit to save 
load save file , deserialise and set it to unit

### Source/destination JSON

```javascript
{"message":"Place your serialized or deserialized JSON here"}
```

### Expected behavior
get a EquipSet which its equipID is {4,-1,-1}

### Actual behavior
 equipID is {-1-1-1,4,-1,-1}

### Steps to reproduce

serialise the equipSet of Unit to save 
load save file , deserialise and set it to unit

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by elgonzo** [comment]
This is intentional behavior.

You have to pay **utmost** attention to the Newtonsoft.Json's default (de)serialization settings, some of which are unfortunatly not what many would expect them to be. For a more detailed explanation of what's going on here and how you can remedy this, see this comment: https://github.com/JamesNK/Newtonsoft.Json/issues/2706#issuecomment-1183252408

**Comment by rere43** [comment]
cool~~  thanks for answering

**Comment by Salemalsh** [comment]
> cool~~  thanks for answering
