### ISSUE TITLE
Collection was modified Error

### ISSUE THREAD

**Issue by Sunlit-ms** [JamesNK/Newtonsoft.Json#2737]
### Problem
I encounter the problem while invoking SerializeList. I have no idea what will cause this problem.
Following is part of my stack:
![image](https://user-images.githubusercontent.com/113427036/189857181-125b4011-011a-4f0e-a8ab-270b4ddf2065.png)

**Comment by elgonzo** [comment]
Well, it seems to me some piece of your is manipulating the list while the serializer is serializing the list. Since List<T> is not thread-safe, this would be exactly the outcome when one thread manipulates the list while another thread iterates over it. Solution to this problem is conceptually simple: Prevent the serialized list from being modified by some other thread while the serializer is processing it. How exactly this should be done depends on your actual code and the logic implemented by it, and i therefore would leave this to you to figure out as you are the one most knowledgable about your own code.

If you find yourself struggling with troubleshooting and fixing your issue, i would then recommend asking on [stackoverflow.com](https://stackoverflow.com) for assistance/suggestions.

If you still think the issue is with Newtonsoft.Json and not with your code, please provide a **minimal** and _complete_ code example demonstrating the issue. Preferably, you may do so by providing a runnable example in [dotnetfiddle.net](https://dotnetfiddle.net) (or other online .NET runtime environments)

**Comment by Sunlit-ms** [comment]
Thanks for your analysis. I will check my code first.
