### ISSUE TITLE
Parsing 0.0 (decimal) different in 13.0.2

### ISSUE THREAD

**Issue by marcovisserFurore** [JamesNK/Newtonsoft.Json#2768]
After using Newtonsoft.Json version 13.0.2, I encountered an unwanted behavior.

### Source/destination types

```csharp
        [TestMethod]
        public void ParseJsonDecimal()
        {
            var json = @"{ ""property"": 0.0}";

            var reader = new JsonTextReader(new StringReader(json))
            {
                FloatParseHandling = FloatParseHandling.Decimal
            };

            while (reader.Read())
            {
                if (reader.TokenType == JsonToken.Float)
                {
                    if (reader.Value is decimal d)
                    {
                        d.ToString(NumberFormatInfo.InvariantInfo).Should().Be("0.0");

                    }
                    else throw new AssertFailedException("Value is not decimal");
                }
            }
        }
```

### Expected behavior

I would expect that the decimal `0.0` contains still the trailing zero after parsing.

### Actual behavior

Decimal looses precision after parsing. The trailing zero (`0.0`) is gone.

### Steps to reproduce
See above unit test.

**Comment by elgonzo** [comment]
Nice catch.

The cause of the issue is in commit https://github.com/JamesNK/Newtonsoft.Json/commit/13717cfc452ee9c1ea0b4fc368b8e9922d562028#diff-188cdcd35a8220c2477c864944a945fa67539c0beac51d3909424ff07dea7fe4 based on this pull request https://github.com/JamesNK/Newtonsoft.Json/pull/2639

Specifically, the `BoxedPrimitives.Get(decimal)` method: https://github.com/JamesNK/Newtonsoft.Json/blob/4fba53a324c445f06ee08e45a015c346000a7ef2/Src/Newtonsoft.Json/Utilities/BoxedPrimitives.cs#L90-L92

For any numerically zero value with trailing zeroes like 0.0, this method unfortunately returns `decimal.zero` which is just 0 without any trailing zeros. I don't know why this had to be hardcoded instead of making it a configurable choice in the JsonTextReader and JsonSerializerSettings...

**Comment by JamesNK** [comment]
Should fix this.

Is there a way to detect whether a decimal has trailing zeroes without ToString? If there is then decimals with trailing zeroes can skip the cache. If there isn't then remove caching of decimals altogether.

**Comment by elgonzo** [comment]
I know of two ways. However, both are available only beginning with .NET 7. 

The following expressions yield _false_ for a zero value _with_ trailing decimal zeros, and _true_ for a zero value without trailing decimal zeros (not sure which of these two would perform better, though):

Using [decimal.IsCanonical(decimal)](https://learn.microsoft.com/en-us/dotnet/api/system.decimal.iscanonical?view=net-7.0#system-decimal-iscanonical(system-decimal)): `decimal.IsCanonical(value) && value == decimal.Zero`

or using [decimal.Scale](https://learn.microsoft.com/en-us/dotnet/api/system.decimal.scale?view=net-7.0#system-decimal-scale): `value.Scale == 0 && value == decimal.Zero`

Dotnetfiddle showing both decimal.IsCanonical and decimal.Scale in action: https://dotnetfiddle.net/qa2XD1

**Comment by JamesNK** [comment]
I think decimal.GetBits, then checking the flags value in the span, should work in .NET 6 - https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Decimal.cs,602

**Comment by JamesNK** [comment]
PR: https://github.com/JamesNK/Newtonsoft.Json/issues/2768

**Comment by jahmai-ca** [comment]
Is this related / will the PR address negative zero (-0.0) is now being (de)serialized as 0 instead of -0?

**Comment by JamesNK** [comment]
> Is this related / will the PR address negative zero (-0.0) is now being (de)serialized as 0 instead of -0?

It's related but doesn't fix it. New PR: https://github.com/JamesNK/Newtonsoft.Json/pull/2777
