### ISSUE TITLE
Default behavior on deserialization of `List<T>` is to append to the collection instead of replacing it.

### ISSUE THREAD

**Issue by tacosontitan** [JamesNK/Newtonsoft.Json#2788]
### Source/destination types

```csharp
public class Sample
{
    public List<int> Integers { get; set; }
    public Sample() =>
        Integers = new List<int> { 1 };
}
```

### Source/destination JSON

```javascript
{
    "integers": [ 2, 3 ]
}
```

### Expected behavior
I expected `Sample.Integers` to contain `2` and `3`.

### Actual behavior
`Sample.Integers` contained `1`, `2`, and `3`.

### Steps to reproduce
```csharp
using Newtonsoft.Json;

string configuration = "{ \"integers\": [ 2, 3 ] }";
var sample = JsonConvert.DeserializeObject<Sample>(configuration);
Console.WriteLine(string.Join(",", sample.Integers));
_ = Console.ReadKey();

public class Sample
{
    public List<int> Integers { get; set; }
    public Sample() =>
        Integers = new List<int> { 1 };
}
```

**Comment by tacosontitan** [comment]
For clarity, this behavior can be changed by specifying `ObjectCreationHandling.Replace` in your `JsonSerializerSettings`. This issue is focused on understanding why the default behavior is to try to add elements to the collection.

**Comment by CZEMacLeod** [comment]
@tacosontitan I think this is mainly to allow scenarios where the constructor creates the collection, and the collection type is custom, or not exposed.

```cs
public class Sample
{
	public IEnumerable<int> Integers { get; set; }
	public Sample() =>
		Integers = new HashSet<int> { 1 };
}
```
If you try this with the following calling code
```cs
		string configuration = "{ \"integers\": [ 2, 3 ] }";
		var ser = new JsonSerializerSettings()
		{
			ObjectCreationHandling = ObjectCreationHandling.Replace
		};
		var sample1a = JsonConvert.DeserializeObject<Sample>(configuration);
		Console.WriteLine(sample1a.Integers.GetType());
		Console.WriteLine(string.Join(",", sample1a.Integers));
		var sample1b = JsonConvert.DeserializeObject<Sample>(configuration,ser);
		Console.WriteLine(sample1b.Integers.GetType());
		Console.WriteLine(string.Join(",", sample1b.Integers));
```
You get 
```
System.Collections.Generic.HashSet`1[System.Int32]
1,2,3
System.Collections.Generic.List`1[System.Int32]
2,3
```
Since the behaviour, requirements, and performance for the class may be improved by using a HashSet instead of a List, and the fact that Newtonsoft.Json cannot tell what type to use, you can initialize the collection beforehand. If you don't, or you force Json.Net to create/replace the collection, it uses `List<T>`.

If 'default' values are added to the collection type, you can always ensure they are cleared before deserializing (without having to use `JsonSerializerSettings` by adding

```cs
	[OnDeserializing]
	internal void OnDeserializingMethod(StreamingContext context)
	{
		(Integers as ICollection<int>)?.Clear();
	}
```
to the `Sample` class.
In this case you get
```
System.Collections.Generic.HashSet`1[System.Int32]
1,2
System.Collections.Generic.List`1[System.Int32]
2,3
```

It should be noted that you can make Integers read only. In this case Newtonsoft.Json will silently 'fail' case b as it cannot replace the object.

```cs
	public IEnumerable<int> Integers { get; }
```
And (assuming you don't have the `OnDeserializing` -> `Clear` function) you get
```
System.Collections.Generic.HashSet`1[System.Int32]
1,2,3
System.Collections.Generic.HashSet`1[System.Int32]
1
```

I grant you that it may not be intuitive in all cases, but it is very powerful (especially if you don't necessarily own all the classes).
Newtonsoft.Json tries to do a lot of stuff for you, and sometimes causes problems because of it (see the issues around date handling). If you want something 'simpler' and more rigid, you might want to use [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json) instead.
