### ISSUE TITLE
If the type file is stored separately in a cs file, OnDeserialized is invalid

### ISSUE THREAD

**Issue by waleywu** [JamesNK/Newtonsoft.Json#2817]
### Source/destination types

```csharp

// DirectoryAccount.cs
public class DirectoryAccount
{
    // normal deserialization
    public string DisplayName { get; set; }

    // these properties are set in OnDeserialized
    public string UserName { get; set; }
    public string Domain { get; set; }

    [JsonExtensionData]
    private IDictionary<string, JToken> _additionalData;

    [OnDeserialized]
    private void OnDeserialized(StreamingContext context)
    {
        // SAMAccountName is not deserialized to any property
        // and so it is added to the extension data dictionary
        string samAccountName = (string)_additionalData["SAMAccountName"];

        Domain = samAccountName.Split('\\')[0];
        UserName = samAccountName.Split('\\')[1];
    }

    public DirectoryAccount()
    {
        _additionalData = new Dictionary<string, JToken>();
    }
}
// test.cs
public void test()
{
     string json = @"{
  'DisplayName': 'John Smith',
  'SAMAccountName': 'contoso\\johns'
}";

DirectoryAccount account = JsonConvert.DeserializeObject<DirectoryAccount>(json);

Console.WriteLine(account.DisplayName);
}
```

### Source/destination JSON

```javascript
{
  'DisplayName': 'John Smith',
  'SAMAccountName': 'contoso\\johns'
}
```

### Steps to reproduce
The DirectoryAccount type is stored in a separate file, then _additionalData.Count ==0. _additionalData.Count ==1 if it is and in the test.cs file, 
```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by elgonzo** [comment]
> If the type file is stored separately in a cs file, OnDeserialized is invalid

> The DirectoryAccount type is stored in a separate file

What? I do not understand. What _exactly_ do you mean? Can you explain by giving a _concrete_ example that reproduces the problem you are having?

**Comment by elgonzo** [comment]
I rather suspect you included the wrong namespace(s) when writing your source code. Because both `Newtonsoft.Json` as well as `System.Text.Json.Serialization` namespaces provide a _JsonExtensionDataAttribute_ type.

And i strongly suspect you included the `System.Text.Json.Serialization` namespace in your source code, therefore the _wrong_ _JsonExtensionDataAttribute_ is being used. Newtonsoft.Json only looks for its own _JsonExtensionDataAttribute_  type contained in the `Newtonsoft.Json` namespace. Therefore, make sure you do not import/use the `System.Text.Json.Serialization` namespace in your DirectoryAccount.cs source code.
