### ISSUE TITLE
JToken parse is returning empty `seq`s

### ISSUE THREAD

**Issue by 64J0** [JamesNK/Newtonsoft.Json#2901]
Hello, hope you're good. I'm trying to parse a stringfied JSON value, but the return is composed of empty `seq`s only. I'm using F# in .NET 7, btw.

### Source/destination types

```csharp
// Put the types you are serializing or deserializing here
```

### Source/destination JSON

```javascript
{
    "ParamA": "1",
    "ParamB": "artifact-00-8",
    "ParamC": "2022-09-01"
}
```

### Expected behavior

To show the `seq`s with their content there.

### Actual behavior

It's showing this:

```bash
m: seq [seq [seq []]; seq [seq []]; seq [seq []]]
```

### Steps to reproduce

```fsharp
#r "nuget: Newtonsoft.Json, 13.0.3"

open Newtonsoft.Json

let jsonData = """{
    "ParamA": "1",
    "ParamB": "artifact-00-8",
    "ParamC": "2022-09-01"
}"""

let m = Linq.JToken.Parse(jsonData)

printfn "m: %A" (m)
```

**Comment by bartelink** [comment]
>I am not the author of the library, 

But you'd make a champion maintainer :P

>You might try using %s instead of %A, 

one tiny correction to an otherwise excellent answer: `%O` is the F# format spec that's used to trigger formatting values via `.ToString()`; `%s` will insist on the expression value being implicitly convertible to a `String` (in general, you're best off using `%s` and then sanity checking the correct way to render a value - `ToString()` can sometimes do the right thing, but esp for things that parse into trees, a one size fits all rendering may not even be what you want in any case)

I'd suggest closing this issue as we're more in F# and/or newtonsoft usage question territory than an actual issue with the library that anyone can do anything specific to resolve.

(I'd also suggest looking at the `FSharp.SystemTextJson` and `System.Text.Json` libraries if you're building something new, unless you're in a system that has standardised on `Newtonsoft.Json`)

**Comment by 64J0** [comment]
Thank you for the great replies and insights @elgonzo and @bartelink.

> I'd suggest closing this issue as we're more in F# and/or newtonsoft usage question territory than an actual issue with the library that anyone can do anything specific to resolve.

Agreed, I'll close this issue now.

**Comment by sungam3r** [comment]
> But you'd make a champion maintainer

100% agree

**Comment by bartelink** [comment]
> 100% agree

That's easy to say for a future co-maintainer :P

**Comment by sungam3r** [comment]
Watching activity here in repo for several years I strongly believe that Json.Net itself has no future.
