### ISSUE TITLE
FloatParseHandling for Serialising data

### ISSUE THREAD

**Issue by samuelcavendish** [JamesNK/Newtonsoft.Json#2905]
When running the following Fiddle https://dotnetfiddle.net/U8DOMu you can see in the output that the Lng value has been changed and an extra decimal place has been added.

Looking at the code it seems the FloatParseHandling changes how values are read but isn't used for writing data

Fiddle code:

```
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public class LatLng
{
	public double Lat { get; set; }

	public double Lng { get; set; }
}

public class Program
{
	public static void Main()
	{
		var item = new LatLng{Lat = 52.585235595703125, Lng = -0.4142917990684509};
		Console.WriteLine(JsonConvert.SerializeObject(item, new JsonSerializerSettings{FloatParseHandling = FloatParseHandling.Decimal, Formatting = Formatting.Indented, Converters = new JsonConverter[]{new StringEnumConverter()}}));
	}
}
```

**Comment by elgonzo** [comment]
No, not a bug in Newtonsoft.Json.

Newtonsoft.Json is not changing the value here, and there are not really "decimal places added". You are just victim of the inherent imprecision of IEEE 754 floating point values. -0.4142917990684509 cannot be precisely stored as a IEEE 754 `double` (64-bit) floating point value. The nearest possible value that can be represented by a `double` value is actually `-0.41429179906845093`.  This behavior is inherent to IEEE 754 floating point values, and you can't avoid this unless you avoid using IEEE 754 floating point types like `float`/`double` (and instead use non-IEEE 754 types like `decimal`, for example).

This being a behavior of the `double` value type and not being caused by Newtonsoft.Json you can very easily see by executing the following code:
```C#
double value = -0.4142917990684509;
Console.WriteLine(value.ToString("G17")); // output with maximum precision
```
The output of this will be, you guessed it, `-0.41429179906845093`.

Also, the setting `FloatParseHandling.Decimal` will have no effect here, because as both the word "Parse" in it indicates as well as [its documentation](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializerSettings_FloatParseHandling.htm) describes:

> Gets or sets how floating point numbers, e.g. 1.0 and 9.9, are **parsed when reading JSON text.**

You are not reading/parsing json text here, you are writing/generting json text.


(Side note unrelated to this particular precision-related behavior you observed, but related to de/serializing float/double values with Newtonsoft.Json: If you are going to de/serialize `double`/`float` values without the FloatParseHandling.Decimal setting, note that Newtonsoft.Json uses the `R` format specifier for floating point values, which is known to have problems in .NET versions earlier than  .NET Core 3.0. So, if you by chance target any .NET version earlier than .NET Core 3.0, you might want to apply a custom `float`/`double` JsonConverter -- as illustrated in https://github.com/JamesNK/Newtonsoft.Json/issues/2889#issuecomment-1695255479 for the `double` type -- to bypass Newtonsoft.Json's float/double conversion routines that are using the `R` specifier.)

**Comment by samuelcavendish** [comment]
Thanks for the response, I appreciate the extra info on core 3 and below

**Comment by sungam3r** [comment]
@elgonzo perfect answer as always 👍
