### ISSUE TITLE
Deserialization of derived type works only when "$type" is first attribute in JSON object

### ISSUE THREAD

**Issue by mikolaj-milewski** [JamesNK/Newtonsoft.Json#2936]
### Source/destination types

```csharp
internal class Base
{
    public string Name { get; set; }
}

internal class Derived : Base
{ }
```

### Source/destination JSON

```javascript
{"Name":"test","$type":"Derived, DeserializationError"}
```

### Expected behavior

I'd like to get instance of `Derived` class.

### Actual behavior

I'm getting instance of `Base` class.

### Steps to reproduce

```csharp
var settings = new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All };

var json1 = "{\"Name\":\"test\",\"$type\":\"Derived, DeserializationError\"}";
var obj1 = JsonConvert.DeserializeObject<Base>(json, settings); // obj1 has Base type

var json2 = "{\"$type\":\"Derived, DeserializationError\",\"Name\":\"test\"}";
var obj2 = JsonConvert.DeserializeObject<Base>(json, settings); // obj2 has Derived type
```

**Comment by elgonzo** [comment]
> Deserialization of derived type works only when "$type" is first attribute in JSON object

Not a bug, and also an incorrect statement. Newtonsoft.Json also supports scenarios where the `"$type"` metadata property is **not** the first property in a Json object.

However, since this pretty much requires the serializer to buffer data (up to the point where it comes across the `"$type"` property), which is incurring both a perf and memory cost, this behavior needs to be _explicitly_ enabled by setting [`JsonSerializerSettings.MetadataPropertyHandling`](https://www.newtonsoft.com/json/help/html/SerializationSettings.htm#MetadataPropertyHandling) to `MetadataPropertyHandling.ReadAhead`.
