### ISSUE TITLE
Deserialization causing System.ExecutionEngineException on Windows Phone 8.1 application

### ISSUE THREAD

**Issue by vncastanheira** [JamesNK/Newtonsoft.Json#362]
This exception is thrown after serializing a big Json file to a Dictionary object and causes the application to crash. It's a collection of links and informations about them.

It was an attempt to deserialize [this json](http://pastebin.com/4xYih9Sk) to [this object type](http://pastebin.com/HCBNMjje).
Does works on a desktop program, but not on mobile.

**Comment by DSchmidlin** [comment]
I am running into this problem on a Windows 10 phone, did you find a solution?

**Comment by GunArm** [comment]
I ran into this problem spontaneously in an application where the code is otherwise in wide use and without problems.  But yes, specifically the symptom occurred when calling Deserialize on Newtonsoft.Json v9.0.1.19813 
Turned out to be indicative of a corrupted .NET framework on the machine.  Running a repair on the .NET framework made the problem go away.
