### ISSUE TITLE
High CPU concumtion in CheckForCircualrReference  for objects with large nested array

### ISSUE THREAD

**Issue by singhsurendra** [JamesNK/Newtonsoft.Json#567]
Noticed very high CPU consumption in CheckForCircualrReference  for an object which has array of other objects. The Equals was overloaded with ToString() which caused O(N^2) ToString() operations just for circular reference check.

Output of the below code (C#):
NestedObject.ToString() Count = 9006000, RootObject.ToString() Count = 3001, RootObject.EqualsCount = 3001

--

public class JsonTest
    {
        public static void test()
        {
            RootObject command = new RootObject();
            string json = JsonConvert.SerializeObject(command);

            Console.WriteLine("NestedObject.ToString() Count = {0}, RootObject.ToString() Count = {1}, RootObject.EqualsCount = {2}", 
               NestedObject.count, command.count, command.EqualsCount);
        }
    }

    public class NestedObject
    {
        public static long count = 0;

        public NestedObject() {}

        public override string ToString()
        {
            count++;
            return base.ToString();
        }
    }

    public class RootObject
    {
        public long count = 0;
        public long EqualsCount = 0;

        public NestedObject  [] Contacts;

        public RootObject()
        {
            Contacts = new NestedObject[3000];
            for (int i = 0; i < 3000; i++)
            {
                Contacts[i] = new NestedObject();
            }
        }

        public override bool Equals(object obj)
        {
            EqualsCount++;
            
            return this.ToString().Equals(obj.ToString());
        }

        public override string ToString()
        {
            count++;
            StringBuilder builder = new StringBuilder();
            foreach (var item in Contacts)
            {
                builder.Append(item.ToString());
            }

            return builder.ToString();
        }
    }

**Comment by D3-LucaPiombino** [comment]
[Again](#401) this is because `object.Equals` should not be used to check for circular references.
If you want to override `object.Equals` to check structural equality you're also forced to take into account that when the object is serialized/deserialized, this can mess with object referential identity.

**The fact the this is the default behavior is, in my opinion, wrong (see pull request #423 for more details)**.
In this case, it cause only performance degradation but in the worst case scenario it will force you to use a proxy type to work around the issue.

I understand that at this point changing the default to use `object.ReferenceEquals` can prove problematic given that someone may relay on the current behavior, but it should at least be possible to *opt-out* from the current behavior.

**Comment by iSynaptic** [comment]
Agreed, I think the default is wrong, but the proposed solution (PR #423) is agreeable. Perhaps 7.0 can make the default use `object.ReferenceEquals`.

**Comment by JamesNK** [comment]
Your Equals implementation is bad. It shouldn't be allocating objects.

I have added an EqualityComparer to JsonSerializer (https://github.com/JamesNK/Newtonsoft.Json/commit/3cc797c24071b35429674205712ed0a5df8cf7ad) but I would recommend fixing your Equals.
