### ISSUE TITLE
Deserializing base64 encoded byte arrays return different results in 2 library versions

### ISSUE THREAD

**Issue by ruhaim** [JamesNK/Newtonsoft.Json#574]
```
  JObject j = JObject.Parse("{'responseArray':'AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA'}");
               
  byte[] r = j["responseArray"].ToObject<byte[]>(JsonSerializer.Create());

  string s = Convert.ToBase64String(r);
```
Deserializing the above code in v6.0.8.18111 gives errorneous result

but the same works properly in v4.5.6.14930

NOTE - the encoded string is a byte array having values 1|0 of length 24
v6.0.8.18111  takes this erroneously as an array of length 17

**Comment by xanatos** [comment]
I think that the breaking change happened between v6.0.3 - v6.0.4

**Comment by dbc2** [comment]
The issue is the base 64 string in question, 'AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAA', also happens to be parsable as a Guid in `JsonReader.ReadAsBytesInternal()`:

            if (s.Length == 0)
            {
                data = new byte[0];
            }
            else if (ConvertUtils.TryConvertGuid(s, out g))
            {
                data = g.ToByteArray();
            }
            else
            {
                data = Convert.FromBase64String(s);
            }

This short-circuits the base 64 conversion.

For an analysis of the problem and workaround, see here:  https://stackoverflow.com/questions/30369274/deserializing-base64-encoded-byte-arrays-return-different-results-in-2-json-net/30384841#30384841

**Comment by JamesNK** [comment]
I can't think of a nice work around.

**Comment by JamesNK** [comment]
Fixed.

GUIDs have to be the 00000000-0000-0000-0000-000000000000 format which will prevent base64 content accidentally being converted to a GUID before being converted to bytes.
