### ISSUE TITLE
KeyValuePairConverter produces result incompatible with DataContractJsonSerializer

### ISSUE THREAD

**Issue by netgh0st** [JamesNK/Newtonsoft.Json#577]
JsonNet uses KeyValuePairConverter (https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/KeyValuePairConverter.cs) which explicitly sets Key and Value field names as, respectively, "Key" and "Value". However, the json, that is produced, cannot be deserialized back to KeyValuePair<TKey,TValue> with DataContractJsonSerializer, because in the actual KeyValuePair .NET type there are private fields key and value, and Key and Value are public getters. So DataContractJsonSerializer throws an exception that it cannot find "key" and "value" in the json.
KeyValuePairConverter should be updated to produce json with "key" and "value" fields instead of "Key" and "Value"

**Comment by IanYates** [comment]
That would be a huge breaking change for anyone relying on the output of `KeyValuePairConverter` (which would probably be anyone actually using it at the moment).  What could make sense would be to either
a) Allow a flag, which defaults to false, to use lowercase field names when serializing; or
b) Provide your own `DataContractCompatibleKeyValuePairConverter' (basically a clone of the `KeyValuePairConverter.cs` file) and modify the two private const string fields; or
c) A mix of (a) and (b) in spirit...  Modify `KeyValuePairConverter` so that it gets `KeyName` and `ValueName` by calling a virtual protected function and then you can just override `KeyValuePairConverter` and implement just that function

**Comment by JamesNK** [comment]
I recommend you write your own KeyValue JsonConverter.

**Comment by netgh0st** [comment]
I think this should actually be fixed. The thing is - Json.Net works perfectly fine when deserializing KeyValuePair with either case, because the uppercase fields match the hard-coded field names, while the lowercase fields are properly mapped to corresponding private fields via reflection.

The below two examples both produce the same valid result:
KeyValuePair<string, string> lowercase = JsonConvert.DeserializeObject<KeyValuePair<string, string>>(@"{ key: ""key"", value: ""value"" }");
KeyValuePair<string, string> uppercase = JsonConvert.DeserializeObject<KeyValuePair<string, string>>(@"{ Key: ""key"", Value: ""value"" }");

So technically if Json.Net starts emitting lowercase key and value for KeyValuePair, it would not break anyone who is using Json.Net to deserialize that Json back. So the only scenarios this could break would be cases when people explicitly rely on the Key and Value being upper case. At the very least this could be made configurable via JsonSettings. I just feel that it's not correct to have such a fundamental type in .NET being serialized in a form not deserializeable with pure reflection (i.e. requiring a custom converter).

**Comment by JamesNK** [comment]
But it would brake anyone using Key/Value in JavaScript

**Comment by netgh0st** [comment]
Fair point. I wonder though how many people use KVPair output from non-.NET code.
Instead of just having a custom KVPair converter, do you think the behavior can be made configurable through JsonSettings? With perhaps 3 options: default (current), DCJS-compatible (lowercase) and "uber" (send out both upper and lower case, twice the payload size, but guaranteed to be compatible)? I can work on a pull request for that if you would consider taking such a change.
