### ISSUE TITLE
Generic JsonConverter?

### ISSUE THREAD

**Issue by Crisfole** [JamesNK/Newtonsoft.Json#585]
It's a bit of a pain to be running casts all over for JsonConverter.  I tried searching the issues and never found a suggestion like this, but instead of copying this around my projects it seems like a good fit for 'core' Newtonsoft.Json:

``` csharp

    public abstract class JsonConverter<T> : JsonConverter {
        public sealed override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
            if (!(value is T)) {
                throw new JsonSerializationException(string.Format("This converter cannot convert {1} of type {0}", value, value.GetType()));
            }
            WriteJson(writer, (T)value, serializer);
        }

        public abstract void WriteJson(JsonWriter writer, T value, JsonSerializer serializer);

        public sealed override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) {
            if (objectType != typeof (T)) {
                throw new JsonSerializationException(string.Format("This converter cannot convert type {0}", objectType));
            }
            if (!(existingValue is T)) {
                throw new JsonSerializationException(string.Format("This converter cannot convert {1} of type {0}", existingValue, existingValue.GetType()));
            }
            return ReadJson(reader, (T) existingValue, serializer);
        }

        public abstract T ReadJson(JsonReader reader, T existingValue, JsonSerializer serializer);

        public sealed override bool CanConvert(Type objectType) {
            return typeof (T) == objectType;
        }
    }
```

By leaving the non-generic intact it makes it feasible to write however crazy a Converter you'd like, but this case covers 99% of the simple cases.

**Comment by Tydude4Christ** [comment]
I really like this suggestion. I use a similar approach to a default parser system I created.

**Comment by hlubovac** [comment]
Somewhat related (same/similar result, but different approach): perhaps this functionality exists and I'm not seeing it, but wouldn't it be better if the `abstract class JsonConverter` had been an interface instead? It's not adding any functionality to the derived class, except forcing it to implement method, for which interfaces are a better fit.

I'm asking this because, because of missing `IJsonConverter` it is very difficult (if not impossible) to properly abstract out the way the to/from serialization is done. To some extent, it is, but if the object being converted needs a JsonConverter that itself also needs application-provided services, then I can't see how they can be injected without either poisoning the custom JsonConverter with the "get-service-from-DI-container" calls or inserting Newtonsoft-specific serialization into the converted-object's class or its converter-class. Somewhat confusing, sorry...

I'm suggesting that you add (or point me to it, if it exists) an interface maybe best named `IJsonConverter` and add overloads to `Serialize` and `Deserialize` methods to take that an array of those instances, then also propagate the similar abstraction into `JsonWriter, JsonReader, JsonSerializer and JsonSchema`. In other words, create this:

```
    public interface IJsonConverter
    {
        void WriteJson(IJsonWriter writer, object value, IJsonSerializer serializer);
        object ReadJson(IJsonReader reader, Type objectType, object existingValue, IJsonSerializer serializer);
        bool CanConvert(Type objectType);
        IJsonSchema GetSchema() { get; }
        bool CanRead { get; }
        bool CanWrite { get; }
    }
```

To me, such change doesn't look extremely difficult to implement: it's more about the will. It seems more logical to me to feed the "serializer" to the "converter" rather than the other way around, because the first is a tool (service) of the latter. Again, maybe I'm wrong or not seeing everything that's related, in which case sorry (but do enlighten me, please).

Thank for reading.

**Comment by TylerBrinkley** [comment]
As #1011 has been merged I believe this issue can be closed.
