### ISSUE TITLE
Newtonsoft.Json.dll release incompatible versions with same strong name

### ISSUE THREAD

**Issue by bondarchook** [JamesNK/Newtonsoft.Json#615]
Newtonsoft.Json release incompatible versions with same strong name, only changing the File version.

Because of this any application, that use Newtonsoft.Json, breaks if other application puts different version of Newtonsoft.Json.dll into the GAC

According to MSDN (https://msdn.microsoft.com/en-us/library/wd40t7ad(v=vs.110).aspx)
"Assemblies that have the same strong name should be identical."

This issue can easily break applications that use microsoft frameworks (e.g. Mircosoft.Data.Odata),
Azure SDK  and others

Every new version (even minor) must have new Assembly version. This is only way .NET can work properly

**Comment by JamesNK** [comment]
If something hurts, stop doing it. Don't put it in the GAC.

**Comment by bondarchook** [comment]
I see you are real professional indeed.
Instead of following rules of platform you are writing for. You decide to F... all who use it.

Problems that this issue implies are very frustrating once. It is not simple error that tell you that it can not load some assembly. It is really convoluted errors.
And alot of products use it. 

Do not use GAC is not an answer. It is simply incompetent solution.

I will just wait until people start reporting problems to microsoft, who by stupidity used your library, and they just fork it and make things right.

**Comment by olivier-spinelli** [comment]
This question makes totally sense.
Following http://semver.org, the .Net assembly version should be set to Major.Minor (so that fix can transparently be applied).
File Version can be set to Major.Minor.[Patch.Build] or whatever increasing numbers you like. (about this file version, may be http://csemver.org could interest you).

**Comment by sergey-litvinov** [comment]
my 5 cents. In some cases there is no other normal choice except GAC. For example Sharepoint uses GAC for packages that we install there, so if two packages use different assemblies but with the same version - dll hell starts again :(

**Comment by olivier-spinelli** [comment]
I totally agrree. And that is why seriously considering SemVer should not be an option...

**Comment by bondarchook** [comment]
@sergey-litvinov 

Yes some time you don`t have control and have to put in GAC
But problem even bigger.

Even if you application does not put this assembly to the GAC but some body else does, It will break your application as well. 

Just imagine your application broken with some strange errors. It is on simple exception "Can not load assembly version ..." no no no it would be Null reference exception some where deep in Newtonsoft.Json or some thing else.

And it is not even your fault. It is just because somebody installed other software, and that software decided to H.J.dll to GAC

**Comment by markusschaber** [comment]
We had similar problems with other assemblies, or solution was to build ourself, using our own snk file, so we get our own "strong name". That way, we can make sure we have unique version numbers, and the framework cannot load wront assemblies because it prefers GAC to local installation directory.
It's a shame that applications cannot suppres loading from GAC (or at least repriorize GAC to be searched after local directories...)
