### ISSUE TITLE
Why do property.Readable and property.Writable default to true with memberserialization == MemberSerialization.Fields?  

### ISSUE THREAD

**Issue by BlackjacketMack** [JamesNK/Newtonsoft.Json#653]
**Issue**
I'm curious what value it adds?  Clearly it's there for a specific purpose.  It's confusing though because if a property has only a 'get' it will get set to 'writable'.  

**Code**

//line 1195 in DefaultContractResolver
if (memberSerialization != MemberSerialization.Fields)
            {
                property.Readable = ReflectionUtils.CanReadMemberValue(member, allowNonPublicAccess);
                property.Writable = ReflectionUtils.CanSetMemberValue(member, allowNonPublicAccess, property.HasMemberAttribute);
            }
            else
            {
                // write to readonly fields
                property.Readable = true;
                property.Writable = true;
            }

**Comment by JamesNK** [comment]
I don't understand what you're asking. It does that because that's how fields serialization works.

**Comment by BlackjacketMack** [comment]
The question is simply this: why would a readonly property (e.g. public string Name{get;}) get marked as 'Writable=true' when using MemberSerialization.Fields?  The backing field may be writable but the property itself is readonly.  Just curious really.  Thanks for your time.

**Comment by Timovzl** [comment]
@BlackjacketMack I was also surprised when I originally learned that the backing fields generated for read-only properties are _not_ given the `readonly` keyword. I have no idea why.

**Comment by Timovzl** [comment]
@sungam3r Well, the `readonly` modifier seems perfectly sensible for the backing fields of get-only auto-properties. If nothing else, having it makes more sense than not having it when inspecting the field through reflection. It could be that it "just wasn't done", as I believe you are implying. Still, it doesn't strike me so much as "having to do something", but rather as a choice between "should we generate the backing field _with_ or _without_ the `readonly` modifier"?

Why, then, did they choose to omit `readonly`? My guess is that the modifier was omitted as a performance optimization for value types. For value types, something like `this._creationDateTime.AddDays(1)` involves an extra copy of the struct if the `_creationDateTime` field is `readonly`. Why the extra copy? Because we cannot easily guarantee that `AddDays()` avoids mutating `this`, but a `readonly` field must not be mutated. (Clearly this does not apply to `readonly structs`, now that we have those. I'm guessing that the backing field generation was simply kept consistent between auto-properties for mutable structs, readonly structs, and classes, i.e. the backing field is simply never made `readonly`.)
