### ISSUE TITLE
Async methods in JsonConvert should be removed

### ISSUE THREAD

**Issue by svick** [JamesNK/Newtonsoft.Json#66]
Because of [a question on SO](http://stackoverflow.com/q/14483218/41071), I went to investigate how does async work in JSON.NET. When I looked at the code (specifically [JsonConvert.cs](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonConvert.cs)), I noticed that the async methods (like [`SerializeObjectAsync()`](https://github.com/JamesNK/Newtonsoft.Json/blob/787bde6e15e6adfb4e606f77fa9d0bd4c7377cc6/Src/Newtonsoft.Json/JsonConvert.cs#L1018)) just call the synchronous version using `Task.Factory.StartNew()`.

This is generally not a good idea, because `Async` methods are usually more scalable than their synchronous version, but this isn't true for your implementation. For more information (and a better explanation), see Stephen Toub's article [_Should I expose asynchronous wrappers for synchronous methods?_](http://blogs.msdn.com/b/pfxteam/archive/2012/03/24/10287244.aspx)

Because of that, I think you should remove the Async versions of your methods from the library.

Where adding `Async` versions would make sense is when working with streams, but doing so would require a lot of changes in classes like `JsonTextReader` (and I'm not sure how to do it without duplicating a lot of code in a way that doesn't break JSON.NET for older versions of .Net).

**Comment by adrianm64** [comment]
I don't get this.
Having SerializeAsync create threads is of course an anti-pattern but why was it removed? Couldn't it just call the Async methods on the underlying writer to get scalability? Currently the only solution to serialize async into a file/network is to store a temporary (i.e. MemoryStream) and then .CopyToAsync().

**Comment by thomaslevesque** [comment]
> Couldn't it just call the Async methods on the underlying writer to get scalability?

It could, but it's not that simple. I tried to do it a few years ago, but gave up after a while. Basically, the problem is that while the sync and async implementations are almost identical, it's hard to extract the common code, so you end up with almost duplicated implementations, which is hard to maintain. And in this case, you need to add async implementations all the way down to JsonReader.

In the typical case, JSON documents are not very large, so the benefit of an async implementation would be marginal, compared to the cost of writing and maintaining the implementation.

**Comment by fretje** [comment]
Now that async support is implemented, couldn't these methods be re-introduced but now with a real async implementation?

I'm not sure how to tackle this though...

I have a DeserializeObjectFromStream method like this:

    public static T DeserializeObjectFromStream<T>(Stream stream, JsonSerializerSettings settings = null)
    {
        var serializer = JsonSerializer.Create(settings);
        T data;
        using (var reader = new StreamReader(stream, Encoding.UTF8))
        {
            data = (T)serializer.Deserialize(reader, typeof(T));
        }
        return data;
    }

How would I go about changing this to use the JObject.LoadAsync method, but still uses the provided serializersettings?

**Comment by JamesNK** [comment]
The helper methods read and write strings which don't have any blocking IO. There is no point.

**Comment by fretje** [comment]
Thanks for the response! But what about that code example in my previous comment? 
When the stream provided is a FileStream, there surely must be some blocking IO involved? Or am I missing something?

**Comment by weitzhandler** [comment]
Async methods would still be useful when serializing to an IO resource.

**Comment by TylerBrinkley** [comment]
This is in regards to `JsonConvert` only, which only reads and writes `string`s. It doesn't have any stream reader/writer support. It would be nice though for async to make it's way to the `JsonSerializer` class.

**Comment by JonHanna** [comment]
@TylerBrinkley I intend to make that my project for the holiday season.

**Comment by petterton** [comment]
@JonHanna Any news on async support for the `JsonSerializer` class? This would be really useful!

**Comment by JonHanna** [comment]
@petterton my OSS output is a bit down of late as my new son isn't as keen on me coding while he sleeps on my chest as my second-youngest was (my output actually went up when second-youngest was born, as I had long periods where coding was the only thing I could do, while he snuggled). It's still on my to-do list, but as I've less coding time right now nobody should see it as a licked cookie if they want to do it.

**Comment by thomaslevesque** [comment]
Now that `JsonWriter` and `JsonReader` support async operations, implementing `SerializeAsync`/`DeserializeAsync` shouldn't be too hard.

**Comment by JonHanna** [comment]
Not terribly. I've a start made, but haven't had a chance to do the necessary tests

**Comment by DrewDaPilot** [comment]
Any progress on this @JonHanna ? I am very interested in an asynchronous serializer!

**Comment by sungam3r** [comment]
System.Text.Json is a way to async serialization-deserialization now.

**Comment by DrewDaPilot** [comment]
@sungam3r does this mean there is no plans to add a async serializer overload?

**Comment by sungam3r** [comment]
I'm 99,99% sure. Just look at the history of this repo. Last significant commit was in November 2019. 475 open issues, 51 open PRs and these numbers are constantly growing. I'm not afraid to say this repo is dead. I have been observing its evolution for quite some time, to be entitled to assert this. **The only thing I don't understand is why the maintainers won't make an official statement about status of Newtonsoft.Json repo so that people no longer waste their time and energy on creating PRs that no one will ever merge**. I read the official MSDN documentation on comparing Newtonsoft.Json and System.Text.Json and there the issue of obsoleting the former was diplomatically bypassed. It was obvious, though. Don't get me wrong, I don't blame anyone for this situation. This is a natural course of things, some projects go down in history, some appear to replace them.
