### ISSUE TITLE
Deserializing properties with internal setters should throw if the property is present in the JSON

### ISSUE THREAD

**Issue by bojanrajkovic** [JamesNK/Newtonsoft.Json#686]
If an object has an internal setter on a property that isn't marked as `JsonIgnore`, the object cannot be cleanly round-tripped. For example, take this object:

```csharp
public class NonGenericObjectTest
    {
        public IDictionary<string, Uri> SyncedObjects { get; set; }
        public SyncState BadDeserialization { get; internal set; }
        public IDictionary<string, ObjectSyncResult> Results { get; set; }
    }
```

Serializing it, we might end up with output like this:

```json
{"SyncedObjects":{"Test":"https://google.com"},"BadDeserialization":1,
"Results":{"Test":{"Created":false,"Errors":[],"Id":"Test","Success":true}}}
```

The `internal` set property `BadDeserialization` is written to the output. However, it can't be roundtripped, because the setter is `internal`, and deserializing the object and reserializing it results in the following:

```json
{"SyncedObjects":{"Test":"https://google.com"},"BadDeserialization":0,
"Results":{"Test":{"Created":false,"Errors":[],"Id":"Test","Success":true}}}
```

Notice that the value is flipped to the default value for the enum, leading to hard-to-track-down bugs. 

IMO, if a property with an internal setter is present in the JSON, the deserializer should throw an exception saying that it can't cleanly deserialize this object, or be able to be configured to do so. This would help catch hard-to-diagnose bugs like this one (I spent about 3 hours tearing my hair out and cursing software before spotting the internal setter).

**Comment by JamesNK** [comment]
MissingMembersHandling.Error will error if JSON can't be deserialized to a property.

**Comment by gakera** [comment]
@JamesNK I tried this just now, and it didn't throw when deserialising? I have an object Response with a `List<Item> Results { get; internal set; }` property. The Item type is just a simple Name+Guid object. 

Calling `JsonConvert.DeserializeObject<Response>(stringResponse);` with a string that should work, results in an object with `Results = Null`. I tried using `MissingMembersHandling.Error`, but still, just silent fail with `Results = Null`. Changing `Results` so that the `set` is not just `internal` fixes it, I now get a `Response` object with the correct `Results` List. But I would have found it quicker if I could tell `DeserializeObject` to throw when it can't create the Results list. 

I can maybe cook up a git example if needed.
