### ISSUE TITLE
Does not deserialize getter-only auto-properties

### ISSUE THREAD

**Issue by azzlack** [JamesNK/Newtonsoft.Json#703]
Getter-only properties in C# are [`readonly`](https://msdn.microsoft.com/en-us/magazine/dn802602.aspx), but they should still be deserialized.

I.e. this does not work (but should) (Tested in v6.0.8):

```csharp
public class MyClass
{
    public string MyProp { get; }
}

...

var r = JsonConvert.DeserializeObject<MyClass>("{\"MyProp\":\"awesome\"}");

Assert.AreEqual("awesome", r.MyProp);
```

However, changing the class to this makes it all work:

```csharp
public class MyClass
{
    public string MyProp { get; private set; }
}
```

These two classes should work the same.

**Comment by eluchsinger** [comment]
Isn't there a difference between the two properties? The first one does not have any Setters. Hence you can't Access it via reflection. The second one has a private setter, which you should be able to Access using reflection. This is just a Supposition.

**Comment by JamesNK** [comment]
There is no way to know where the value for a setter only property comes from. The second class provides a way to set the the property that just happens to be private.

**Comment by xxMUROxx** [comment]
@JamesNK: I use following code to write a value to a readonly property:

~~~csharp
public class T
{
    public string Test { get; }
}

[Test]
public void TestSetReadonlyProperty()
{
    T testObject = new T();

    var property = testObject .GetType().GetProperty("Test");
    if (!property.CanWrite)
    {
        var field = testObject .GetType().GetField($"<{p.Name}>k__BackingField",
                                                   BindingFlags.NonPublic | BindingFlags.Instance);
        field?.SetValue(testObject , "ahah");
    }

    Assert.That(t.Test, Is.EqualTo("ahah"));
}
~~~~

**Comment by khellang** [comment]
> There is no way to know where the value for a setter only property comes from.

Fortunately, OP isn't talking about a setter-only properties...

This is about *getter-only auto properties*, which means there *is* a way to know where the value comes from:

Since it's an auto property, it has a compiler-generated backing field.

The only difference between a getter-only auto property and one with a setter is that the backing field is `readonly` and thus can't be assigned through the property outside the constructor. However, this doesn't mean that Newtonsoft.Json couldn't assign the backing field directly, like @xxMUROxx's solution.

**Comment by NickCraver** [comment]
I agree this should be supported - we've added the same functionality to Protobuf and Dapper for all of the similar scenarios people run into.

**Comment by TylerBrinkley** [comment]
I disagree that this should be supported. If you have a getter-only auto property it should be assigned in the constructor or else add a private setter to the property. That way you're not relying on C# auto property generation implementation details that may change from version to version.

**Comment by ekevoo** [comment]
Does any other serialization solution support this scenario?

**Comment by NickCraver** [comment]
@TylerBrinkley How do you propose we do the constructor route (in general) when just deserializing any object? For most users we run into, they expect a getter-only property to be populated when you serialize/deserialize it. That's why we've added such functionality to Dapper and protobuf (@ekevoo's question) .

Just adding a private setter isn't so straightforward. That can easily be a performance impact since the JIT can no longer treat it as a readonly which enables a wide range of assumptions and optimizations.

I'm not arguing for this to be a default behavior, I'm simply saying it should be an easy-to-accomplish task.  Yes, for the moment it is implementation dependent, so it'd be better if there was one copy of that implementation match in NuGet to update rather than every app doing the contracts themselves.

**Comment by mebjas** [comment]
I guess this have been implemented as of now, right?

**Comment by robgha01** [comment]
I found this today ben working on solving a bugg and it is exactly this issue the 3rd party model that i try to decompile has only one constructor parameter of type JToken token and the class handles the properties by itself "its auto get-only" properties however when i do 
`object value = token.ToObject(prop.PropertyType, serializer);.`

the serializer is not smart and ignores that it has only a constructor parameter of JToken here it would be nice if it understands that hey the properties is not writable but we set the value anyway, passing in the token or doing the above mentioned stuff ?

what is the status of this ?

**Comment by JamesNK** [comment]
Not supported

**Comment by xxxcodeine** [comment]
Why is this closed?

**Comment by JamesNK** [comment]
For the reason I said?

**Comment by xxxcodeine** [comment]
@JamesNK I saw some workaround with using `[JsonConstructor]`

**Comment by TylerBrinkley** [comment]
To me, if a property is not assignable purely within code then why should it be assignable through a deserializer? I mean, Visual Studio should give you warnings that a getter only auto property is never assigned to as it can only be assigned within a constructor without resorting to hacking it with reflection.

**Comment by kbrownhbs** [comment]
I agree with Salgat.

If I use a JsonSerializer to serialize an object, I expect using the same JsonSerializer to deserializer the resultant json to return the original object.
_(so long as the original object had no ignore properties)_

**Comment by TylerBrinkley** [comment]
In that scenario, how are you initializing that object to serialize in the first place if not as a constructor parameter?

**Comment by kbrownhbs** [comment]
Because I like working with immutable object, I am initializing using a
constructor that has parameters for each object property.
See below

    public sealed class CreateUserCommand
    {
        public UserId UserId { get; }
        public EmailAddress Email { get; }
        public UserRole UserRole { get; }

        public CreateUserCommand(UserId userId, EmailAddress email,
UserRole userRole)
        {
                   UserId = userId;
                   ....
        }
     }

Annotating the constructor of every object in the hierarchy with
[JsonConstructor] works, but I would prefer to avoid polluting my POCO with
annotations if possible.

**Comment by JamesNK** [comment]
`[JsonConstructor]` is only required when there are multiple constructors.

**Comment by JamesNK** [comment]
`[JsonConstructor]` is only required when there are multiple constructors. If you want multiple constructors and you don't want attributes then you can write a contract resolver that chooses the desired constructor.

**Comment by ViceIce** [comment]
C# 7.3 has a new [backing field attributes](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-3#attach-attributes-to-the-backing-fields-for-auto-implemented-properties) feature.

Shouldn't it be possible to deserialize the auto-property with adding  `JsonPropertyAttribute` to the backing field?

```c#
class Test {
  [field: JsonProperty("Num")]
  public int Num { get; }
}
```

**Comment by TylerBrinkley** [comment]
@ViceIce I thought that might work with adding a `JsonIgnoreAttribute` to the property but it still doesn't because the backing field is readonly and it appears they aren't supported either.

**Comment by v-kydela** [comment]
Newtonsoft seems to be incredibly clever about finding ways to populate read-only members. Consider the following scenario:

```c#
public class MyClass
{
	public MyClass(string prop1, string someName)
	{
		Prop1 = prop1;
		Prop2 = someName;
	}

	public string Prop1 { get; }
	public string Prop2 { get; }
}
```

When deserializing this class, Newtonsoft will be able to populate `Prop1` because it sees a parameter named `prop1` in the constructor:

```c#
Console.WriteLine(
	JsonConvert.SerializeObject(
		JsonConvert.DeserializeObject<MyClass>(
			"{\"Prop1\":\"foo\",\"Prop2\":\"bar\"}")));

// {"Prop1":"foo","Prop2":null}
```

Unfortunately this makes Newtonsoft easy to fool. You could do a little switcheroo in the constructor to have Newtonsoft deserialize the class incorrectly:

```c#
public MyClass(string prop1, string prop2)
{
	Prop2 = prop1;
	Prop1 = prop2;
}
```

It seems to me like it would be both easier and more accurate to have Newtonsoft just deserialize read-only members using reflection, but I understand that some developers would prefer to avoid reflection in their libraries to adhere to the principle of least surprise.

**Comment by TonyValenti** [comment]
Is there a way to make this happen?  I have a hard time believing that Newtonsoft can't deserialize readonly properties.  The cost on reflection should essentially be a one-time-per-app extremely minimal overhead:

````
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Reflection;

namespace JsonTests {
    class Program {
        static void Main(string[] args) {

            var C = new Foo2();
            Setter<Foo2>.Set(C, "Name", "Hello");
            Setter<Foo2>.Set(C, "Age", 21);

            Console.WriteLine(C.Name);
            Console.WriteLine(C.Age);

        }

    }


    public static class Setter<T> {

        static Dictionary<string, Action<T, object>> Cache = new Dictionary<string, Action<T, object>>(StringComparer.InvariantCultureIgnoreCase);

        static Setter() {

            //var Props = typeof(T).GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.GetProperty | BindingFlags.SetProperty);
            var Props = typeof(T).GetProperties();

            foreach (var item in Props) {
                Cache[item.Name] = CreateSetter(item);
            }
        }

        public static void Set<V>(T Target, string PropName, V Value) {
            if (Cache.TryGetValue(PropName, out var Setter)) {
                Setter(Target, Value);
            }
        }

        public static Action<T, object> CreateSetter(PropertyInfo P) {
            var ret = default(Action<T, object>);

            ParameterExpression oParam = Expression.Parameter(typeof(T), "obj");
            ParameterExpression vParam = Expression.Parameter(typeof(object), "val");
            MethodCallExpression mce = Expression.Call(oParam, P.SetMethod, Expression.Convert(vParam, P.PropertyType));

            var action = Expression.Lambda<Action<T, object>>(mce, oParam, vParam);

            ret = action.Compile();

            return ret;
        }


        public static Action<T, TValue> CreateSetter<TValue>(Expression<Func<T, TValue>> memberLamda) {
            var ret = default(Action<T, TValue>);

            var memberSelectorExpression = memberLamda.Body as MemberExpression;
            if (memberSelectorExpression != null) {
                var property = memberSelectorExpression.Member as PropertyInfo;
                if (property != null) {

                    ParameterExpression oParam = Expression.Parameter(typeof(T), "obj");
                    ParameterExpression vParam = Expression.Parameter(typeof(TValue), "val");
                    MethodCallExpression mce = Expression.Call(oParam, property.SetMethod, vParam);
                    Expression<Action<T, TValue>> action = Expression.Lambda<Action<T, TValue>>(mce, oParam, vParam);

                    ret = action.Compile();


                }
            }

            return ret;
        }
    }


    public class Foo2 {
        public string Name { get; set; }
        public int Age { get; private set; }
    }

}

````

**Comment by MichaelPuckett2** [comment]
This needs to be re-opened if it's not already implemented.  Having immutable DTO's is more ideal than even private setters and I know it can be done because I do it all the time with reflection.  Please reopen.

**Comment by cesarfp** [comment]
I'm having the same issue, I can't deserialize this class

public class SecretItem
{
        public SecretItem() { }
        public SecretIdentifier Identifier { get; }
 }

**Comment by BrianOstrander** [comment]
Not trying to revive this from the dead, but since it's the first result on Google for "get only auto properties newtonsoft" I thought I'd leave a writeup I did the help any souls who totally nuked their codebase with `{ get; }` and provide them with a possible -- albeit aggravating -- solution. [Hope this helps.](https://gist.github.com/BrianOstrander/ef793a36a00106db50cf1c57ce656151)

**Comment by v-kydela** [comment]
@BrianOstrander - Did you see my comment? Newtonsoft deserializes getter-only properties using constructor parameter names.

**Comment by BrianOstrander** [comment]
@v-kydela Yes, your answer helped me fully explore the scope of the problem I had and the solutions available to me, however it was not a realistic solution for me. I felt I misused the get only auto property, and that requiring a constructor to be kept up to date was not ideal, for some of the very reasons you mentioned in your comment -- it's easy to fool Newtonsoft. Thank you though!

**Comment by zahirtezcan-bugs** [comment]
> 
> ```
> 
> However, changing the class to this makes it all work:
> 
> 
> public class MyClass
> {
>     public string MyProp { get; private set; }
> }
> 

It does not work if `MyProp` returns a custom value-types. For such case, `MyProp` explicitly needs a public set operation.

**Comment by sake402** [comment]
I don't thing getter only property should be deserialized.
While you may be able to get away with in by using the backing field, it will soon break if the compiler change the name of the backing field in the future.

Also how could we expect to deserialize when there is no backing field as NewtonSoft will have no way of differentiating.

```
public class Foo{
    public string Name{ get; }
}
```
from
```
public class Foo{
    public string Name=>"MyName";
}
```

**Comment by MichaelPuckett2** [comment]
First, I've been doing this for years now so if it changes you have to update but it works.  Second, your first example is a readonly property and it's not the same as your second example using expression bodied properties. 
public Count { get;}
is not the same at all as 
public Count => count; for example and the same applies if you're assigning a constant
public Count => 5; for example.  They work completely different.
Finally, C# 9 is solving this with records anyway so all the naysays out there that don't understand true immutability and the need for it won't have to argue about it anymore.
Making a class deserializable and not immutable is the same as making a string a List of char as opposed to the immutable string.  We should be allowed to deserializer true immutable types just like we do any other types and therefore not require the class to be designed to work differently just because we plan on using Newtonsoft to do the work.  It's ok though, Newton won't do it then the community will and has, we make our own now and will continue to do so.

**Comment by sake402** [comment]
Yes they are not the same, internally. But from the external perspective of the deserializer or the property caller, they are. Being bodied expression or auto property is encapsulated within the class and I as the class user won't know the difference.

My point is that an attempt by the deserializer to deserialize to ``public Count => 5`` will certainly fail while ``public Count { get; }`` will not, even though they look alike from outside the class.

**Comment by MichaelPuckett2** [comment]
That's not fair.  It's the job of the deserializer now to determine which one it is and how to handle it.  You can get the difference via reflection.

**Comment by eltomek** [comment]
> Newtonsoft seems to be incredibly clever about finding ways to populate read-only members. Consider the following scenario:

Good one! However, if there is more than one constructor in the deserialzed class it stops working. Any way to indicate Newtonsoft to ignore the specific constructor?

**Comment by v-kydela** [comment]
@eltomek - Did you try the `JsonConstructorAttribute` solution mentioned in this discussion?

**Comment by eltomek** [comment]
> @eltomek - Did you try the `JsonConstructorAttribute` solution mentioned in this discussion?

Yes, I've seen it however it is not doable in case one doesn't have access to the deserialized object's class code. Unless there's a way to add the attribute in run-time which I haven't figured out how to do yet.

**Comment by alexmgerasimov** [comment]
We could do something like this:

```
public class SampleClass
{
    [field: JsonProperty("Property")]
    [JsonIgnore]
    public string Property { get; } = "PropertyValue";
}

const string json = "{\"Property\":\"NEW-PropertyValue\"}";

var serializerSettings = new JsonSerializerSettings
{
    ContractResolver = new DefaultContractResolver
    {
	// this settings is needed to work with compiler-generated backing fields
        SerializeCompilerGeneratedMembers = true
    }
};

var deserializedSample = JsonConvert.DeserializeObject<SampleClass>(json, serializerSettings);

```
If you need to do this in older C# version or have no control over attributes, you could override CreateProperty() method of DefaultContractResolver with something like this:

```
protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
{
    var jsonProperty = base.CreateProperty(member, memberSerialization);

    if (jsonProperty.Writable == false)
    {
	// this uses compiler implementation details and may not work for all cases
	// better to use smarter approach like in BackingFieldResolver from Mono.Reflection library
        var fieldInfo = jsonProperty.DeclaringType.GetField($"<{jsonProperty.PropertyName}>k__BackingField",
            BindingFlags.NonPublic | BindingFlags.Instance);

        if (fieldInfo != null)
        {
            jsonProperty.ValueProvider = new ReflectionValueProvider(fieldInfo);
            jsonProperty.Writable = true;
        }
    }
        
    return jsonProperty;
}

```

**Comment by icodev-space** [comment]
> [JsonConstructor]

Bro your observation saved my Friday evening!
