### ISSUE TITLE
Unable to find ctor for immutable list

### ISSUE THREAD

**Issue by kentcb** [JamesNK/Newtonsoft.Json#722]
Hi,

I have this test code:

```C#
var data = new[]
{
    "first",
    "second",
    "third"
}.ToImmutableList();
var settings = new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.All
};
var serialized = JsonConvert.SerializeObject(data, settings);
Debug.WriteLine("SERIALIZED: " + serialized);
var deserialized = JsonConvert.DeserializeObject<ImmutableList<string>>(serialized, settings);
Debug.WriteLine("DESERIALIZED #" + deserialized.Count);
```

It executes fine inside a PCL that is running on the full framework (which surprised me when I first tried it, because how does it know how to rehydrate the immutable list?). However, when running on top of Xamarin (Android) I get:

```
Newtonsoft.Json.JsonSerializationException : Unable to find a constructor to use for type System.Collections.Immutable.ImmutableList`1[System.String]. Path '$values', line 1, position 124.
```

Is this expected? If I need to have immutable lists inside my serializable data structures, what is the best way for me to facilitate them?

**Comment by kentcb** [comment]
Oh, I see it [should work](http://james.newtonking.com/archive/2013/10/14/json-net-5-0-release-7-immutable-collections)?

**Comment by IanYates** [comment]
I use immutable collections all the time without too much issue.
There is one thing I've come across, particularly as I also use a library/toolkit called ImmutableObjectGraph (it's on GitHub).

If you have the immutable list as a read-only (getter) property on your class you may need to help JSON.Net work out how to get the existing immutable list (and it better not be null) and then store the updated list back in the property.

In my ImmutableObjectGraph objects, if I leave the default value of a list as null then JSON.Net chokes on them.  Having them non-null, which makes more sense anyway, allows JSON.Net to get on with its job.  (although I need to use a contract resolver to get JSON.Net to go via a Builder type created by ImmutableObjectGraph first).

The specific issue you described sounds like a related but separate issue since you're just looking to deserialise an immutableList directly but, if you actually have properties involved, I'm hoping the above may be of some help.

**Comment by JamesNK** [comment]
What dll from the NuGet package is being referenced in your app?

**Comment by kentcb** [comment]
@JamesNK: packages\Newtonsoft.Json.7.0.1\lib\portable-net40+sl5+wp80+win8+wpa81\Newtonsoft.Json.dll

@IanYates: thanks for the info. In my actual use case, I do expose immutable lists via read-only properties. I simplified things right down for the repro, but even the unsimplified code works fine when running on the desktop FX.

**Comment by JamesNK** [comment]
Adding support for immutable to this build has already been done but not released - https://github.com/JamesNK/Newtonsoft.Json/commit/239cde86f0f458863f76f063a09eb7fc0d64ecfa

**Comment by kentcb** [comment]
Oh, cool. Any idea when it will be released?

**Comment by JamesNK** [comment]
Yes
