### ISSUE TITLE
JsonProperty Order is not being considered on deserialization

### ISSUE THREAD

**Issue by cangosta** [JamesNK/Newtonsoft.Json#758]
The Order  property works fine for serialization, but the it is not being considered on deserialization. According to the documentation, the order attribute is used for both serialization and deserialization. Is there a workaround?

**Comment by JamesNK** [comment]
Where does it say that?

Deserialization happens in the order that properties appear in the JSON object.

**Comment by cangosta** [comment]
Hi James, thanks for your answer. There it is: http://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_JsonProperty_Order.htm

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/e04f0eec486ddd7c2a3209a6591f89f1ebd69da7

**Comment by cangosta** [comment]
There are some cases in which the order of deserialization does matter... 

Suppose I'm serializing a LinqToSql model with some associations, e. g. a User model with EnterpriseID and the Enterprise object itself. In this case, if the Enterprise field is deserialized before the EnterpriseID, I get a ForeignKeyReferenceAlreadyHasValueException when deserializing the EnterpriseID field. 

It would be nice having the deserialization process consider the defined order, otherwise how could I solve this problem?

**Comment by brunocunhasilva** [comment]
Hi,
I don't agree with this "fix" - removing the deserialization word from the documentation.
The same way the order is relevant when serializing an object, it's also important, for some use cases, that the order is respected when deserializing the object, especially when you can't control the way the JSON strings are created - e.g. the javascript JSON serializer creates the JSON string with the object properties in alphabetical order.

**Comment by JamesNK** [comment]
It's not going to happen because loading the entire document into memory will kill performance. All deserializers (DataContractSerializer, DataContractJsonSerializer, XmlSerializer, JavaScriptSerializer) set properties based on the order of values in the data.

**Comment by reddyBell** [comment]
Just to vote for that, even though I don't have any performance fix do propose. 

I routinely have situations where read-only properties need to use values not deserialized yet, this results in a code polluted with confusing null checks ("why would this property ever be null ?").

For example 

`public override Money CommissionToPay
        {
            get
            {
                if (Product== null) //Deserialization stage
                    return null;

                return Price * Product.CommissionRate.Value;
            }
        }`

The workaround I'm considering is to favour methods over computed properties moving forward, but I find it sad to impact my APIs that way since :

1/ These read-only values need to be serialize
2/ The topology of properties seems to be the most expressive and appropriate in many cases. 

But, thinking out loud, perhaps the very act of calling a method, and saving the changed value of a readonly property as a known side-effect is not a discutable design to start with. I'm thinking that perhaps, an object is expected to be serialize, computed properties should be avoided since using them means, asking the client to know the side effects and internals of our components. The client should probably always explicitly know when is persistence should be updated.

If this is indeed the case, then the need to an ordered deserialization is no longer exists altogether.
 Just to say that  this feature could actually be of the type "if you need it, you are doing something wrong"™

**Comment by IanYates** [comment]
I appreciate it probably doesn't help with the LinqToSql case described above, but for the case described by @reddyBell I'd have my object initialised via constructor parameters.  You avoid half-constructed objects and messy state that way.  Having something sourced externally, like some JSON, be applied to an object that's brittle enough to behave unpredictably when the properties are set out of order (or missing!) sounds like a problem I'd rather avoid.

I suspect custom contracts, with a contract resolver, are a way to solve this problem too.  You could deserialize in that contract to some dictionary or property bag, then read your object's properties, assess the attributes and assign in the order you determine.  I appreciate it's boilerplate code but it could be made universal and then even released as a separate NuGet package if anyone is so inclined.

I've seen this "separate package" suggestion a few times from @JamesNK lately and there's some merit to the pay-for-play approach.  Having them discoverable a wiki would be handy but otherwise it keeps JSON.Net focussed but still extensible.

Another thought: you could use a DTO that consists of simple getters/setters and then create your real object with something like AutoMapper?

**Comment by TTWill** [comment]
Of **cause** it can be respected for deserialization, that is if @JamesNK would agree that a proper **fix** is not about removing a feature due to regression, but instead require an order in which properties are presented **before** deserialization. You can add it as an option to require the order to be respected. Sounds pretty simple to me.

**Comment by ylatuya** [comment]
We have a custom ORM that uses JSON.Net to persist objects to Couchbase.Lite. In the deserialization process, we read the object from a Couchbase.Lite document that returns a dictionary of unordered properties.

To support deserialization of forward references, when you have no choice and don't mind reading the entire document in memory,  we use a custom `IReferenceResolver` named  `LookAheadReferenceSolver`. It works like the `DefaultReferenceResolver`, except when it can't resolve a reference, it traverses the container and builds a dictionary of references to resolve it.

It's not generic enough and performs poorly in most scenarios, but it works well enough for our particular use case. I will include the implementation here in case anyone needs it.

```
internal class LookAheadReferenceResolver (JsonSerializer serializer, SerializationContext context, JObject container) : IReferenceResolver
	{
		const string ID_PROPERTY_NAME = "$id";
		const string TYPE_PROPERTY_NAME = "$type";

		readonly Dictionary<string, object> referenceToObject = new ();
		readonly Dictionary<object, string> objectToReference = new ();

		Dictionary<string, JObject> referenceToJobject;

		readonly JObject container = container;
		readonly JsonSerializer serializer = serializer;
		readonly SerializationContext serializationContext = context;

		int referencesCount = 0;

		public void AddReference (object context, string reference, object value)
		{
			if (!referenceToObject.ContainsKey (reference)) {
				referenceToObject[reference] = value;
			}
			if (!objectToReference.ContainsKey (value)) {
				objectToReference[value] = reference;
			}
		}

		public string GetReference (object context, object value)
		{
			if (objectToReference.TryGetValue (value, out var reference)) {
				return reference;
			}
			AddReference (context, referencesCount.ToString (), value);
			referencesCount++;
			return reference;
		}

		public bool IsReferenced (object context, object value)
		{
			return objectToReference.ContainsKey (value);
		}

		public object ResolveReference (object context, string reference)
		{
			referenceToObject.TryGetValue (reference, out var value);
			if (value == null) {
				referenceToJobject ??= BuildIdMap (container);
				if (!referenceToJobject.TryGetValue (reference, out var obj)) {
					return null;
				}
				var typeStr = obj[TYPE_PROPERTY_NAME].ToString ();
				Type objType = serializationContext.Binder.BindToType (typeStr);
				value = referenceToJobject[reference].ToObject (objType, serializer);
			}
			return value;
		}

		Dictionary<string, JObject> BuildIdMap (JContainer container)
		{
			return container
				.Descendants ()
				.OfType<JObject> ()
				.Where (obj => obj.ContainsKey (ID_PROPERTY_NAME))
				.ToDictionary (obj => (string)obj[ID_PROPERTY_NAME], obj => obj);
		}
	}
```
