### ISSUE TITLE
Problems when deserializing objects with a byte array property in version 8.0.1

### ISSUE THREAD

**Issue by larsmichael** [JamesNK/Newtonsoft.Json#778]
The problem is described in details here: http://stackoverflow.com/questions/34654184/unable-to-deserialize-an-object-with-a-byte-array-property-using-json-net-8-0-1

**Comment by dbc2** [comment]
The problem seems to be as follows.

In Json.NET version 7, `JsonTextReader.ReadAsBytes()` called `JsonReader.ReadAsBytesInternal()`.  In the latter, the reader was advanced past the end of the wrapped type object by via a call to `ReadInternal()`:

        internal byte[] ReadAsBytesInternal()
        {
            // SNIP

            if (IsWrappedInTypeObject())
            {
                byte[] data = ReadAsBytes();
                // Here the reader is advanced past the wrapped type object end-of-object token '}' 
                ReadInternal();
                SetToken(JsonToken.Bytes, data, false);
                return data;
            }

In Json.NET 8.0 the equivalent logic takes place in `JsonTextReader.ReadAsBytes()`:

        public override byte[] ReadAsBytes()
        {
            EnsureBuffer();

            switch (_currentState)
            {
                case State.Start:
                case State.Property:
                case State.Array:
                case State.ArrayStart:
                case State.Constructor:
                case State.ConstructorStart:
                case State.PostValue:
                    while (true)
                    {
                        char currentChar = _chars[_charPos];

                        switch (currentChar)
                        {
                            // SNIP
                            case '"':
                            case '\'':
                                ParseString(currentChar, ReadType.ReadAsBytes);
                                // Notice there is no call to consume the wrapped type object end-of-object token '}' 
                                return (byte[])Value;

The call to advance the reader past the wrapped type object end-of-object token `}` is missing.  

There were several check-ins refactoring this area for 8.0 so I'm not sure which one introduced the issue.

**Comment by ascholz81** [comment]
+1

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/70120ce0779f1d2c73a0226d04e0015cadf4cf47

Using 7.0.1 until 8.0.2

**Comment by JamesNK** [comment]
https://www.nuget.org/packages/Newtonsoft.Json/8.0.2

**Comment by larsmichael** [comment]
That was fast :) I am impressed. Thanks

lør. 9. jan. 2016 04.00 skrev James Newton-King <notifications@github.com>:
