### ISSUE TITLE
CamelCasePropertyNamesContractResolver uses obsolete shareCache option

### ISSUE THREAD

**Issue by TFleury** [JamesNK/Newtonsoft.Json#830]
Issue described in #321, but closed by author without being solved.

If you inherit a custom `ContractResolver` from `CamelCasePropertyNamesContractResolver`, which is intended to just change property names casing, shared cache is forced.

**Comment by JamesNK** [comment]
It's not good but changing it would be a breaking change.

**Comment by TFleury** [comment]
Can you at least provide a way to disable shared cache without changing default behavior ?
Changing access modifier of `_sharedCache` to `protected` would allow overriding this behavior in a derived ContractResolver constructor without introducing a breaking change.

**Comment by pedrofelixsky** [comment]
Agree. The default static shared caching behavior is problematic in composition scenarios where a composite resolver is dispatching to different resolver based on type characteristics.
At least, the `CamelCasePropertyNamesContractResolver` should provide a ctor that disables shared caching.

**Comment by heaths** [comment]
Just got bit by this ourselves. It took a bit to track down, and offering a constructor overload would also make it more obvious - not to mention allow us to extend `CamelCasePropertyNamesContractResolver` without caching.

**Comment by AArnott** [comment]
This was closed based on the idea that it would be a breaking change, but in fact #1078 proves it can be done without a breaking change. But that PR was rejected, because it *used to be possible* another way. Now that way is also cut off. What are we supposed to do so that we don't have to define a specialized type for every single variation we might need at runtime for this?
