### ISSUE TITLE
Deserialize with array attribute

### ISSUE THREAD

**Issue by uetkaje** [JamesNK/Newtonsoft.Json#834]
Hi everyone,

First example works as I expected.
```c#
// First example
string js = "{ name: 'uet', images: [ 1 ] }";
XmlDocument xml = JsonConvert.DeserializeXmlNode(js, "response", true);
Console.WriteLine(xml.OuterXml);
/*
Output: 
<response>
<name>uet</name>
<images json:Array="true" xmlns:json="http://james.newtonking.com/projects/json">1</images>
</response>
*/
```

But, It does not work when array length greater than one.
```c#
// Second example
string js = "{ name: 'uet', images: [ 1, 2 ] }";
XmlDocument xml = JsonConvert.DeserializeXmlNode(js, "response", true);
Console.WriteLine(xml.OuterXml);
/*
Output: 
<response>
<name>uet</name>
<images>1</images>
<images>2</images>
</response>
*/
```
The output should be;
```c#
/*
Output: 
<response xmlns:json="http://james.newtonking.com/projects/json">
<name>uet</name>
<images json:Array="true">1</images>
<images json:Array="true">2</images>
</response>
*/
```

I can not realize, how to accomplish this. Or Is it bug at [line 1859](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/XmlNodeConverter.cs#L1859)?

Any help would be appreciated.

**Comment by uetkaje** [comment]
I've done by changing the line at [1839](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/XmlNodeConverter.cs#L1859) as follows;
```C#
if (count == 1 && WriteArrayAttribute)
{
    IXmlElement arrayElement = currentNode.ChildNodes.OfType<IXmlElement>().Single(n => n.LocalName == propertyName);
    AddJsonArrayAttribute(arrayElement, document);
}
else if (count > 1 && WriteArrayAttribute)
{
    IEnumerable<IXmlElement> arrayElements = currentNode.ChildNodes.OfType<IXmlElement>().Where(n => n.LocalName == propertyName);
    foreach (IXmlElement e in arrayElements)
    {
        AddJsonArrayAttribute(e, document);
    }
}
```

How about this?

**Comment by gina36s** [comment]
Hello I am running into the same issue.  Is this a known bug?

**Comment by CameronJayBarton** [comment]
It seems weird at first that it doesn't include the array attribute on a collection of more than one, but it might be intentional.  When deserializing from xml back to json it seems to work fine without the array attribute when there is more than one element with the same name at the same nesting level.  It only needs the extra information of the array attribute if the collection size is one - that's the only case where it's array-like nature isn't self-evident from the standard xml.

In the below example we can tell NewThings should be an array even without the array attribute, but we wouldn't know that CurrentThings is supposed to be part of an array without it.

![image](https://user-images.githubusercontent.com/83244508/117086714-fa94bb80-ad12-11eb-8b55-2daf9074a81b.png)
![image](https://user-images.githubusercontent.com/83244508/117086723-fe284280-ad12-11eb-8aa4-8a8f867ec0f8.png)
