### ISSUE TITLE
JValue.ToString() is not InvariantCulture

### ISSUE THREAD

**Issue by antonovicha** [JamesNK/Newtonsoft.Json#874]
JValue.ToString() uses current thread culture instead of CultureInfo.InvariantCulture.
There is no way to specify culture for this call.
And documentation does not states anything regarding this call (unfortunately). Could be that this is intended behavior?

Here is unit test that shows this issue:
```
// Arrange
var json = @"{ ""Prop"": 5.6 }";
Thread.CurrentThread.CurrentCulture = new CultureInfo("en-Gb", true)
{
	NumberFormat = new NumberFormatInfo
	{
		NumberDecimalSeparator = ">>>"
	}
};

// SUT
var obj = (JToken)JsonConvert.DeserializeObject(json);

// Act
var result = obj["Prop"].ToString();

// Assert
result.Should().Be("5.6"); // Expected "5.6" but got "5>>>6"
```

I will try to look into sources & create a unit test for this case.

**Comment by JamesNK** [comment]
If you want the result to be culture invariant then you can cast the token to `JValue` and call `ToString(CultureInfo.InvariantCulture)`

The idea of ToString on JValue is as if you were calling ToString on the internal value, which defaults to respecting the current culture.

**Comment by antonovicha** [comment]
Hi JamesNK, stupid me, how do I miss it. Probably because we are operating on JToken. But ofcourse we can use JValue instead.

**Comment by luhu** [comment]
@JamesNK does JValue take the culture info from current thread consider to be by deign? I didn't find any documentation regarding it here: https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Linq_JValue_Value.htm

I have a piece of code like below:
```
string json = "{\"ratio\":0.5,\"datetime\":\"2019-07-17T10:21:07.913Z\"}";
JObject o = JObject.Parse(json);
foreach (JProperty p in o.Properties())
{
     Console.WriteLine("{0}: {1}", p.Name, **p.Value**);
}
```
What I expected  - it consistently output
```
ratio: 0.5 // 0 point 5
datetime: 7/17/2019 10:21:07 AM
````
However, if the culture is pt-BR for example, I get 
```
ratio: 0,5 // 0 comma 5
datetime: 17/07/2019 10:21:07 // notice time format
```
This can cause tricky bugs. 

Is there a way I can configure InvariantCulture globally for JValue instead of change the culture info of the current thread or use `ToString(CultureInfo.InvariantCulture)` in all places which looks redundant? 

Thanks!
