### ISSUE TITLE
EmitDefaultValue = false makes the member not populated with default value

### ISSUE THREAD

**Issue by ardpx** [JamesNK/Newtonsoft.Json#88]
Hi,

I found in Json.net v5.0.5 that if the member is marked as EmitDefaultValue = false, the deserialization will not set the default value for the member when the DefaultValuehandling is IgnoreAndPopulate. Is that by design or a bug? 

Because I need to support both XML and Json, I'd like to use [DataMember(Name, EmitDefaultValue..)] for both formats.

Here's the testing code,

static void Main(string[] args)
{
        string str = "{}";
        var obj = JsonConvert.DeserializeObject<TestClass>(str, new JsonSerializerSettings
        {
            DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate
        });
            // obj.Field1 == "fff";
}

[DataContract]
public class TestClass
{
    [DataMember(EmitDefaultValue = false)]
    [DefaultValue("fff")]
    public string Field1 { set; get; }
}

**Comment by lassevk** [comment]
A question popped up on Stack Overflow today - https://stackoverflow.com/questions/60565409/newtonsoft-json-not-deserializing-field-marked-with-emitdefaultvalue

Can you explain why this impacts *deserialization*? I ask because you say it is like picking the DefaultValueHandling.Ignore on a property, and let me paraphrase the current documentation from this:

> Ignore members where the member value is the same as the member's default value **when serializing objects** so that it is not **written*** to JSON. This option will ignore all default values (e.g. null for objects and nullable types; 0 for integers, decimals and floating point numbers; and false for booleans). The default value ignored can be changed by placing the DefaultValueAttribute on the property.

*(my emphasis)*

So why does this impact **de**serialization at all?
