### ISSUE TITLE
Why JsonConverterAttribute is sealed?

### ISSUE THREAD

**Issue by tohidazizi** [JamesNK/Newtonsoft.Json#887]
Is there a good reason that JsonConverterAttribute is sealed? 
Isn't it work better if we can inherite from it and make our custom converter cleaner? 

    public class MyJsonConverterAttribute : JsonConverterAttribute
    {
        public MyJsonConverterAttribute ()
            : base(typeof(MyConverter))
        { }
    }

Or even better: Can it convert to an interface, like: IJsonConverterAttribute ?

    public class MyJsonConverterAttribute : Attribute, IJsonConverterAttribute
    {
        public Type ObjectType { get; set; }
    }

**Comment by JamesNK** [comment]
I'd prefer to leave it sealed. Specifying the converter type like you've done would be the only advantage and I don't think it is much of one.

**Comment by MrAntix** [comment]
it allows us to add extra properties to the attribute for serialization

```
public class WrapperAttribute : JsonConverterAttribute
{
    public WrapperAttribute (string name)
        : base(typeof(MyConverter))
    { 
        Name = name;
    }

    public string Name { get; private set; }
}
```

this would add a wrapper around the property decorate by the attribute

**Comment by falahati** [comment]
+1 

Disappointed it got rejected and closed, I don't like the fact that my library users have to add a reference to Newtonsoft.Json simply because they want to decorate one of their classes using one the converters in the library when in fact all the serialization and deserializations happens inside the library and it shouldn't matter for the library user which underlying library is used for Json serialization.

**Comment by JechoJekov** [comment]
@JamesNK

As @JamesNK this makes the code more readable and slick. It also makes it possible to configure a converter in a more elegant way rather than specifying a constructor parameters. For example,

```C#
[Trim(RemoveDuplicateWhitespace = true)]
public string Name { get; set; }
```

> Allowing a derived class breaks the current constraint that only one JsonConverterAttribute on a type or member.

JSON.NET can simply throw an exception if there are more than one converter attributes on a property.

**Comment by fluffynuts** [comment]
I'd like to chip in a "me too" here: my code is littered with:

```
[JsonConverter(typeof(StringEnumConverter), true)]
```

If I could derive, I could make something neater like:
```
[SerializeAsString]
```

which would also be less befuddling for anyone else who stumbles on the project and has to figure out what I'm doing -- in particular, why I need the boolean parameter.

Personally, I think that allowing more powerful use of the library trumps enforcing a single instance -- we're all adults here: if I break something by doing the wrong thing, then that's on me. The serializing code could just use the first one it comes across and let the chips fall where they may.

**Comment by peterdrier** [comment]
+1, for all the reasons above. 

My perception seems to indicate a much stronger technical argument for than against.  Or I'm totally missing something..

**Comment by peterdrier** [comment]
> just how it ends up being.

ironic given the guide states: "Json.NET has many extensibility points, it is possible you can implement your feature today without modifying Json.NET". 

I'd gather to bet that forcing a second type to be involved every time negates any performance/memory improvements of sealing.  OO wise, there's a small argument that (for example) your "SerializeAsString" is Not a "JsonConverterAttribute" per se. Though I'd easily classify the exception for that case as worthy given the improved readability were I bestowed the dictatorial magic wand. 

I literally have thousands of these across a good 50 projects I'm involved in..  The more I've evolved to embrace attribute based coding, the more roadblocks like this annoy me.  c'est la vie..

**Comment by develorem** [comment]
Worth noting that System.Text.Json.Serialization.JsonConverterAttribute is NOT sealed. 
For us, we have custom strings for how we serialize dates and times. This code is copy/pasted across hundreds of models. 
We want our own attribute that inherits from JsonConverterAttribute for two reasons:
1. Lets us ensure the same formatter is used without a developer 'mistake' on the formatting string
2. Gives us a point of abstraction so that we can migrate to System.Text.Json later
Also it just looks cleaner.

**Comment by DirkBoer** [comment]
I agree with this. 

Extending code for a readability is valid argument. All these extra braces  [xxx(yyy=zzz)]  is very tiring to read.

"0.1% of the people might use it for a bad practice (in their own code!), let's punish the other 99.9%".

**Comment by fluffynuts** [comment]
> To be fair, I would prefer this to be fixed on a C# level (i.e. allow to inherit from sealed classes, but not allow protected methods to be accessed)

whilst I'm a proponent of unsealing this attribute, the whole point of sealing is to enable perf benefits by ensuring that there's no vtable lookups, so there will never (by definition) be the ability to inherit from sealed classes - it's like saying "I'd like to be able to access private members directly". Of course, the latter can be achieved via reflection.

**Comment by douglasg14b** [comment]
This also gives us the ability to make custom converters that may have additional contextual information for our own JSON converters for awkward serialization use cases.
