### ISSUE TITLE
JsonConvert.DeserializeObject leads to blocking UI thread by garbage collector in Windows 10 UWP

### ISSUE THREAD

**Issue by vadim-tsedrik** [JamesNK/Newtonsoft.Json#894]
In Windows 10 UWP when i'm trying to deserialize collection by using JsonConvert.DeserializeObject<T> with 1000+ elements. And it blocks UI thread by too often call of garbage collection as a result. 
In Windows Phone 8.1 the same code works fine.
` private void StartButton_OnClick(object sender, RoutedEventArgs e)
        {          
            Task.Factory.StartNew(async () =>
            {
                var storageFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///trips.json"));
                var content = await FileIO.ReadTextAsync(storageFile);

                for (int i = 0; i < 100; i++)
                {
                    var trips = JsonConvert.DeserializeObject<IEnumerable<Trip>>(content);
                    if (trips != null)
                    {
                        var result = new List<Trip>(trips);
                    }
                }
            });
        }`
You can see reports from diagnostics tool from here: http://stackoverflow.com/questions/36891854/why-garbage-collection-is-running-too-often-in-windows-10-uwp-app
In demo project you can see that UI cannot be blocked by GC in Windows Phone 8.1, and in Windows 10 UWP it's blocked by GC every time you click the button.
[GC_Test.zip](https://github.com/JamesNK/Newtonsoft.Json/files/240894/GC_Test.zip)

**Comment by JamesNK** [comment]
I profiled your memory usage and Json.NET isn't causing your issue.

Removing the `RaisePropertyChanged` (or changing them to take a string instead of a delegate) cuts memory usage by 80%. Also you want to deserialize from a Stream instead of loading the entire string into memory, and you should deserialize to a `List<Trip>` directly.

http://www.newtonsoft.com/json/help/html/Performance.htm

You can donate for services rendered here: https://pledgie.com/campaigns/18941
