### ISSUE TITLE
SerializeObject NotImplementedException .Net Core

### ISSUE THREAD

**Issue by schwietertj** [JamesNK/Newtonsoft.Json#999]
When trying to serialize an object a NotImplementedException occurs.

`var json = JsonConvert.SerializeObject(result);`

**Generated Error**
An unhandled exception occurred while processing the request.

NotImplementedException: The method or operation is not implemented.
WriteJson

**Software Version Information**
.Net Core 1.0
Newtonsoft.Json 9.0.1

**Comment by IanYates** [comment]
Out of curiosity, what kind of object is `result`?  Do you have properties on it that throw `NotImplementedException` when their getters are invoked?  Is there a stack trace to go with the exception?
My gut feeling is that this isn't an issue in JSON.Net (aka "select isn't broken").

**Comment by schwietertj** [comment]
You maybe right with your gut feeling. I have been doing some further testing to see if this is a false issue but I need some guidance. 

If I am returning a JsonResult, does the .Net framework use Newtonsoft to serialize an object? If so, are there any unfinished features in reflection that could cause this error? 

The object, Stripe.StripeCharge,  is the response from charging an account using a token. The reason for me to serialize the response is to store the json string into a database table. 

I will get the requested information when I get back to the office in the morning (-4 gmt). 

Thank you very much for your time and assistance.

**Comment by pieceofsummer** [comment]
I'd rather bet on a custom JsonConverter for some property/data type involved, which supports only deserialization. 

Briefly looking at the code, I can guess it is [`SourceConverter`](https://github.com/jaymedavis/stripe.net/blob/master/src/Stripe/Infrastructure/SourceConverter.cs) for `Source` property.

You'd better create a new DTO class to store in database (which you can control), rather than rely on entities you don't own, and which may change with the next update of API library.

**Comment by JamesNK** [comment]
The exception is coming from a method called WriteJson which indicates to me that a custom JsonConverter you're using is throwing it.
